#!/usr/bin/env -S "make_github_workflows"
version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    groups:
      pre-commit:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      pip-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
