#!/bin/bash

set -e -f -u -o pipefail

dest_dir() {
  local hostname="$1" subdir="$2"
  printf "%s/%s\\n" "${hostname}" "${subdir}"
}

ssh_key_basename() {
  local hostname="$1" subdir="$2"
  printf "%s_%s\\n" "${hostname}" "${subdir}"
}

ssh_key_path() {
  local hostname="$1" subdir="$2"
  printf "%s/.ssh/rsync-net/%s\\n" "${HOME}" \
    "$(ssh_key_basename "${hostname}" "${subdir}")"
}

print_setup_instructions() {
  local hostname="$1" subdir="$2"
  local ssh_key ssh_key_path dest_dir
  ssh_key="$(ssh_key_basename "${hostname}" "${subdir}")"
  ssh_key_path="$(ssh_key_path "${hostname}" "${subdir}")"
  dest_dir="$(dest_dir "${hostname}" "${subdir}")"

  printf "Create a key with:\\n"
  printf "$ ssh-keygen -t rsa -b 4096 -o -f %s -C rsync-net_%s\\n" \
    "${ssh_key_path}" "${ssh_key}"
  printf "Add the key to authorized_keys:\\n"
  printf "command=\"rsync --server -vlogDtpre.iLsfxC . %s\",%s PUB_KEY\\n" \
    "${dest_dir}" "no-pty,no-agent-forwarding,no-port-forwarding"
}

usage() {
  printf "%s HOSTNAME SUBDIR SOURCE_DIR\\n" "$0"
  printf "E.g. %s johntobin-laptop Documents /Users/johntobin/Documents\\n" "$0"
}

main() {
  if [[ "$#" -ne 3 ]]; then
    usage
    exit 1
  fi

  local hostname="$1" subdir="$2" source_dir="$3"
  local ssh_key_path
  ssh_key_path="$(ssh_key_path "${hostname}" "${subdir}")"
  if [[ ! -f "${ssh_key_path}" ]]; then
    printf "Missing SSH key :(\\n" >&2
    print_setup_instructions "${hostname}" "${subdir}" >&2
    exit 1
  fi

  # Make sure we use the right key rather than any inherited keys.
  unset SSH_AUTH_SOCK
  local dest_dir flags=() exit_status=0
  if [[ -t 0 ]]; then
    printf "Backing up %s\\n" "${source_dir}"
    # Progress indicator when run interactively.
    flags+=("--info=progress2,stats" "--progress" "--verbose")
  fi
  dest_dir="$(dest_dir "${hostname}" "${subdir}")"
  # TODO: suppress output
  # https://git.samba.org/?p=rsync.git;a=blob_plain;f=support/rsync-no-vanished;hb=HEAD
  rsync --archive --bwlimit=100K --delete \
    --rsh="ssh -i ${ssh_key_path}" \
    "${flags[@]}" \
    "${source_dir}/" "rsync-net:${dest_dir}/" \
    || exit_status="$?"
  # 24 is a magic exit code that means some files disappeared during the
  # transfer; replace 24 with 0 so we exit successfully.
  if [[ "${exit_status}" == 24 ]]; then
    exit_status=0
  fi
  return "${exit_status}"
}

main "$@"
