#!/bin/bash

set -e -f -u -o pipefail

source "${HOME}/bin/backup-to-rsync-net-lib"

main() {
  if [[ "$#" -eq 0 ]]; then
    echo "Usage: $0 [--make-keys-only] HOSTNAME"
    return 1
  fi

  local backup_config
  for backup_config in $(< "${HOME}/.config/backups/dirs-to-backup"); do
    local destination directory
    IFS=":" read -r destination directory <<< "${backup_config}"
    directory="${directory/#\~/${HOME}}"
    # Only backup if the directory is writable, so unprivileged users don't try
    # to backup /etc.
    if [[ -d "${directory}" && -w "${directory}" ]]; then
      backup "$@" "${destination}" "${directory}"
    fi
  done

  if all_backups_succeeded; then
    backup-update-rsync-net-sentinel "$@"
  fi
}

main "$@"
