#!/bin/bash

set -e -f -u -o pipefail

# shellcheck disable=SC1090
source "${HOME}/bin/backup-to-rsync-net-lib"

readonly hostname="johntobin-imac"
backup "$@" "${hostname}" backups "${HOME}/backups"
backup "$@" "${hostname}" Documents "${HOME}/Documents"
backup "$@" "${hostname}" Media_ArianeStuff_FromOldLaptops \
  "${HOME}/Media/ArianeStuff/From-old-laptops"
backup "$@" "${hostname}" Pictures_Lightroom "${HOME}/Pictures/Lightroom"
if all_backups_succeeded; then
  update-rsync-net-sentinel "$@" "${hostname}"
fi
