#!/bin/bash

set -e -f -u -o pipefail

source "${HOME}/bin/backup-to-rsync-net-lib"

main() {
  if [[ "$#" -eq 0 ]]; then
    echo "Usage: $0 [--make-keys-only] HOSTNAME"
    return 1
  fi

  # Ensure it can't accidentally use the wrong key.
  unset SSH_AUTH_SOCK

  local backup_configs=() line
  while IFS='' read -r line; do
    backup_configs+=("${line}");
  done < "${HOME}/.config/backups/dirs-to-backup"

  local backup_config
  for backup_config in "${backup_configs[@]}"; do
    local destination directory
    IFS=":" read -r destination directory <<< "${backup_config}"
    directory="${directory/#\~/${HOME}}"
    # Only backup if the directory is writable, so unprivileged users don't try
    # to backup /etc.
    if [[ -d "${directory}" && -w "${directory}" ]]; then
      backup "$@" "${destination}" "${directory}"
    fi
  done

  all_backups_succeeded
}

main "$@"
