#!/bin/bash

set -e -f -u -o pipefail

source "${HOME}/bin/backup-to-rsync-net-lib"

readonly hostname="arianetobin-personal-2019-laptop"
backup "$@" "${hostname}" Desktop "${HOME}/Desktop"
backup "$@" "${hostname}" Documents "${HOME}/Documents"
backup "$@" "${hostname}" Downloads "${HOME}/Downloads"
backup "$@" "${hostname}" Pictures "${HOME}/Pictures"
if all_backups_succeeded; then
  backup-update-rsync-net-sentinel "$@" "${hostname}"
fi
