#!/bin/bash

set -e -f -u -o pipefail

source "${HOME}/bin/backup-to-rsync-net-lib"

readonly hostname="hosting"
backup "$@" "${hostname}" etc /etc
backup "$@" "${hostname}" wordpress-backups /home/johntobin/wordpress-backups
backup "$@" "${hostname}" arianetobin.ie /var/www/sites/arianetobin.ie/blog
backup "$@" "${hostname}" dev.arianetobin.ie /var/www/sites/dev.arianetobin.ie
if all_backups_succeeded; then
  backup-update-rsync-net-sentinel "$@" "${hostname}"
fi
