#!/bin/bash

set -e -f -u -o pipefail

# shellcheck disable=SC1090
source "${HOME}/bin/backup-to-rsync-net-lib"

readonly hostname="johntobin-laptop"
backup "$@" "${hostname}" CalibreLibrary "${HOME}/Calibre Library"
backup "$@" "${hostname}" Documents "${HOME}/Documents"
backup "$@" "${hostname}" Pictures "${HOME}/Pictures"
if all_backups_succeeded; then
  update-rsync-net-sentinel "$@" "${hostname}"
fi
