#!/bin/bash

set -e -f -u -o pipefail

readonly destdir="/Volumes/Backup/"
readonly srcdir="/Volumes/Data/"

if [[ ! -d "${destdir}" ]]; then
  printf "Missing destination: %s\\n" "${destdir}" >&2
  exit 1
fi

if [[ ! -d "${srcdir}" ]]; then
  printf "Missing source: %s\\n" "${srcdir}" >&2
  exit 1
fi

sudo rsync -a --verbose \
  --hard-links \
  --delete \
  --exclude='.*' --exclude='hourly.*' \
  "${srcdir}" "${destdir}"

retry() {
  local sleep_time=10
  until "$@"; do
    sleep "${sleep_time}"
  done
}
unmountdisk() {
  local type="$1" disk
  # sync and sleep so hopefully data is fully flushed and unmounting succeeds.
  sync
  sleep 5
  disk="$(diskutil list \
            | awk '$3 == "Backup" && $2 == "'"${type}"'" { print $6 }' \
            | sed -e 's/s[[:digit:]]$//')"
  printf "unmounting %s which is %s\\n" "${type}" "${disk}"
  diskutil unmountdisk "${disk}"
}
# Unmount the disks, starting with the filesystem and then doing CoreStorage.
retry unmountdisk "Apple_HFS"
retry unmountdisk "Apple_CoreStorage"
