#!/bin/bash

set -e -f -u -o pipefail

# If the top-level code was called with -x, then enable it in child processes
# too.
export SHELLOPTS

__NUM_FAILED_BACKUPS=0
__VERBOSE=0
if [[ -t 0 ]]; then
  __VERBOSE=1
fi
backup() {
  if ! backup-single-directory-to-rsync-net "$@"; then
    ((++__NUM_FAILED_BACKUPS))
  fi
}

all_backups_succeeded() {
  if [[ "${__NUM_FAILED_BACKUPS}" -ne 0 && "${__VERBOSE}" == 1 ]]; then
    # Only show error when interactive because I don't want output in cron jobs.
    printf "%d failed backups\\n" "${__NUM_FAILED_BACKUPS}" >&2
  fi
  return "${__NUM_FAILED_BACKUPS}"
}

dest_dir() {
  local hostname="$1" subdir="$2"
  printf "%s/%s\\n" "${hostname}" "${subdir}"
}

ssh_key_basename() {
  local hostname="$1" subdir="$2"
  printf "%s_%s\\n" "${hostname}" "${subdir}"
}

ssh_subdir_path() {
  printf "%s/.ssh/rsync-net\\n" "${HOME}"
}

ssh_key_path() {
  local hostname="$1" subdir="$2"
  printf "%s/%s\\n" "$(ssh_subdir_path)" \
    "$(ssh_key_basename "${hostname}" "${subdir}")"
}

make_ssh_key() {
  local hostname="$1" subdir="$2"
  local ssh_key ssh_key_path dest_dir
  ssh_key="$(ssh_key_basename "${hostname}" "${subdir}")"
  ssh_key_path="$(ssh_key_path "${hostname}" "${subdir}")"
  dest_dir="$(dest_dir "${hostname}" "${subdir}")"
  mkdir -p "$(ssh_subdir_path)"

  ssh-keygen -t rsa -b 4096 -o -N '' -q \
    -f "${ssh_key_path}" -C "rsync-net_${ssh_key}"

  printf "command=\"rsync --server"
  printf " -vlogDtpre.iLsfxC"
  printf " --delete"
  printf " --partial-dir .rsync-partial"
  printf " . %s/\"" "${dest_dir}"
  printf ",no-pty,no-agent-forwarding,no-port-forwarding "
  cat "${ssh_key_path}.pub"
}

check_ssh_key_exists() {
  local options="$1" hostname="$2" subdir="$3" make_keys_only="$4" ssh_key_path
  ssh_key_path="$(ssh_key_path "${hostname}" "${subdir}")"
  if [[ -f "${ssh_key_path}" ]]; then
    return 0
  fi
  printf "Missing SSH key :( %s\\n" "${subdir}" >&2
  if [[ "${make_keys_only}" -eq 1 ]]; then
    make_ssh_key "${options}" "${hostname}" "${subdir}"
    return 0
  fi
  return 1
}

run_rsync() {
  local hostname="$1" subdir="$2" source_dir="$3"
  local dest_dir ssh_key_path
  dest_dir="$(dest_dir "${hostname}" "${subdir}")"
  ssh_key_path="$(ssh_key_path "${hostname}" "${subdir}")"

  # Make sure we use the right key rather than any inherited keys.
  unset SSH_AUTH_SOCK
  local flags=()
  flags+=("--delete" "--delete-excluded")
  flags+=("--filter=dir-merge rsync-net_filters")
  flags+=("--filter=dir-merge,- .gitignore")
  if [[ "${__VERBOSE}" == 1 ]]; then
    printf "Backing up %s\\n" "${source_dir}"
    # Progress indicator when run interactively.
    flags+=("--info=progress2,stats" "--progress" "--verbose")
  fi
  flags+=("${source_dir}/" "rsync-net:${dest_dir}/")

  # Save the exit status if rsync fails so that it can be checked for the magic
  # value 24, which is a magic exit code that means some files disappeared
  # during the transfer.
  local exit_status=0
  rsync --archive --bwlimit=20M \
        --partial-dir=.rsync-partial --partial \
        --rsh="ssh -i ${ssh_key_path} -o PasswordAuthentication=no" \
        "${flags[@]:+${flags[@]}}" \
    || exit_status="$?"
  # Replace 24 with 0 so we exit successfully.
  if [[ "${exit_status}" == 24 ]]; then
    exit_status=0
  fi
  return "${exit_status}"
}
