#!/bin/bash

set -e -f -u -o pipefail

readonly destdir="mini:/Volumes/Data/backups/JohnStuff/"
readonly srcdir="/Volumes/Johns Stuff/"

if [[ ! -d "${srcdir}" ]]; then
  echo "Missing source: ${srcdir}" >&2
  exit 1
fi

# --exclude='.*' is used to skip various directories like .Trashes and
# .Spotlight-* that Mac OS manages.
rsync --archive --verbose --human-readable \
  --one-file-system --delete --exclude='.*' \
  --rsync-path=/usr/local/bin/rsync \
  "${srcdir}" "${destdir}"
