#!/bin/bash

set -e -f -u -o pipefail

readonly destdir="mini:/Volumes/Data/backups/JohnStuff/"
readonly srcdir="/Volumes/Johns Stuff/"

if [[ ! -d "${srcdir}" ]]; then
  echo "Missing source: ${srcdir}" >&2
  exit 1
fi

# 1MB limit to make the network usable for others.
bwlimit=1024
if ifconfig | grep -q -F 192.168.0.100; then
  # Don't limit bandwidth when running over localhost.
  bwlimit=0
fi

# --exclude='.*' is used to skip various directories like .Trashes and
# .Spotlight-* that Mac OS manages.
rsync --archive --verbose --human-readable \
  --one-file-system --delete --exclude='.*' \
  --rsync-path=/usr/local/bin/rsync \
  --bwlimit="${bwlimit}" \
  "${srcdir}" "${destdir}"
