#!/bin/bash

set -e -f -u -o pipefail

readonly destdir="/Volumes/Backup/"
readonly srcdir="/Volumes/Data/"

if [[ ! -d "${destdir}" ]]; then
  echo "Missing destination: ${destdir}" >&2
  exit 1
fi

if [[ ! -d "${srcdir}" ]]; then
  echo "Missing source: ${srcdir}" >&2
  exit 1
fi

sudo rsync -a --verbose \
  --hard-links \
  --delete \
  --exclude='.*' --exclude='hourly.*' \
  "${srcdir}" "${destdir}"

# Unmount the disks, starting with the filesystem and then doing CoreStorage.
repeat() {
  local i times="$1"
  shift
  for i in $(seq 1 "${times}"); do
    echo "repeat: ${i}/${times}"
    "$@"
    sleep 5
  done
}
retry() {
  local sleep_time=10
  until "$@"; do
    sleep "${sleep_time}"
  done
}
unmountdisk() {
  local type="$1" disk
  # sync and sleep so hopefully data is fully flushed and unmounting succeeds.
  sync
  sleep 10
  echo "unmounting ${type}"
  # diskutil list | awk | diskutil unmount fails; maybe separating them will
  # work?
  disk="$(diskutil list \
            | awk '$3 == "Backup" && $2 == "'"${type}"'" { print $6 }')"
  diskutil unmountdisk "${disk}"
}
repeat 5 retry unmountdisk "Apple_HFS"
repeat 5 retry unmountdisk "Apple_CoreStorage"
