#!/bin/bash

set -e -f -u -o pipefail

source "${HOME}/bin/backup-to-rsync-net-lib"

usage() {
  printf "Usage: %s HOSTNAME DAYS\\n" "$0" >&2
}

generate_contents() {
  local sentinel_dir="$1"
  shift
  if [[ "$#" -ne 2 ]]; then
    usage
    return 1
  fi
  local hostname="$1" max_days="$2"
  printf "%d\\n" "$((60 * 60 * 24 * max_days))" \
    > "${sentinel_dir}/${hostname}.max_allowed_delay"
}

main() {
  update_sentinel_file "$@"
}

main "$@"
