#!/bin/bash

set -e -f -u -o pipefail

# IDEA:
# - Create a tmp file named ${hostname} and put seconds since the epoch in
#   there.
# - Rsync that file to a directory on rsync.net; same directory for all hosts
#   (so --nodelete).
# - On imac rsync that entire directory down (all 5 files) and check each file
#   for how old the timestamp inside is.
# - If all the timestamps are old then something is wrong globally - alert after
#   1 day for that.
# - If 1 timestamp is bad then that machine is probably off - alert after 5 days
#   maybe?  I'll need some way to mark machines that are expected to be
#   unavailable, e.g. a file named ${hostname}.returns in that directory that
#   gives the timestamp the machine is expected back; that way a stale file
#   won't silence the alert for ever.
