#!/bin/bash

set -e -f -u -o pipefail

# config.sh needs to define the following variables:
# - RESTIC_REPOSITORY    - repository to backup to.
# - RESTIC_PASSWORD_FILE - file containing the password for the repository.
# - DIRS_TO_BACKUP       - array of directories to backup.
source "${HOME}/.config/backup-restic/config.sh"
export RESTIC_REPOSITORY RESTIC_PASSWORD_FILE
# Fix permissions, just in case.
chmod 700 "$(dirname "${RESTIC_PASSWORD_FILE}")" "${RESTIC_PASSWORD_FILE}"

restic backup --quiet "${DIRS_TO_BACKUP[@]}"
