#!/bin/bash

set -e -f -u -o pipefail

source "${HOME}/bin/backup-to-rsync-net-lib"

usage() {
  printf "Usage: %s\\n" "$0"
}

main() {
  if [[ "$#" -ne 0 ]]; then
    usage
    return 1
  fi

  # This requires that "retrieve" is a symlink to "update".
  local hostname_for_key="retrieve" subdir="sentinel"
  check_ssh_key_exists --pull "${hostname_for_key}" "${subdir}" 0

  local destdir
  destdir="$(mktemp -d -t sentinel.XXXXXXXXXX)"
  # I want ${destdir} to be expanded now, because when we exit successfully it
  # will be out of scope and cannot be expanded.
  # shellcheck disable=SC2064
  trap "rm -rf \"${destdir}\"" EXIT

  run_rsync --pull "${hostname_for_key}" "${subdir}" "${destdir}"
  "${HOME}/bin/check_backup_sentinels" "${destdir}"
}

main "$@"
