#!/bin/bash

set -e -f -u -o pipefail

readonly destdir="mini:/Volumes/Data/backups/Photos/"
readonly srcdir="/Volumes/Ariane Stuff/Photos/"

if [[ ! -d "${srcdir}" ]]; then
  echo "Missing source: ${srcdir}" >&2
  exit 1
fi

rsync --archive --info=progress2,stats --human-readable \
  --exclude='.*' --one-file-system \
  --delete \
  --rsh="ssh -l arianetobin" --rsync-path=/usr/local/bin/rsync \
  "${srcdir}" "${destdir}"
