#!/bin/bash

set -e -f -u -o pipefail

# shellcheck disable=SC1090
source "${HOME}/bin/backup-to-rsync-net-lib"

usage() {
    printf "Usage: %s [--test-keys-only] HOSTNAME\\n" "$0" >&2
}

main() {
  # TODO: this is repetitive, figure out a better way.  Also when checking SSH
  # key existence.
  local test_keys_only=0
  if [[ "$#" -eq 2 && "$1" == "--test-keys-only" ]]; then
    test_keys_only=1
    shift
  fi
  if [[ "$#" -ne 1 ]]; then
    usage
    return 1
  fi

  local hostname="$1" hostname_for_key="update" subdir="sentinel"
  if ! check_ssh_key_exists --nodelete "${hostname_for_key}" "${subdir}" \
         "${test_keys_only}"; then
    return 1
  fi
  if [[ "${test_keys_only}" -eq 1 ]]; then
    return 0
  fi

  local sentinel_dir
  sentinel_dir="$(mktemp -d -t sentinel_dir.XXXXXXXXXX)"
  # I want ${sentinel_dir} to be expanded now, because when we exit
  # successfully it will be out of scope and cannot be expanded.
  # shellcheck disable=SC2064
  trap "rm -rf \"${sentinel_dir}\"" EXIT
  date -u '+%s' > "${sentinel_dir}/${hostname}"
  run_rsync --nodelete "${hostname_for_key}" "${subdir}" "${sentinel_dir}"
}

main "$@"
