#!/bin/bash

set -e -f -u -o pipefail

files_changed_in_dir() {
  local dir="$1"
  git diff --cached --name-only --diff-filter=ACM \
    | grep "^${dir}/"
}

if files_changed_in_dir tests; then
  make -C tests
fi

if files_changed_in_dir python; then
  ( cd python
    pytest
    set +f
    pylint -- *.py
    mypy -- *.py
    set -f)
fi
