#!/bin/bash

set -e -f -u -o pipefail

files_changed_in_dir() {
  local dir="$1"
  git diff --cached --name-only --diff-filter=ACM \
    | grep "^${dir}/"
}

# Unconditionally run these tests because properly checking whether running them
# is necessary would duplicate the Makefile.  If nothing has changed this is a
# no-op, if something has changed the tests are fast and need to be run.
make -C tests

if files_changed_in_dir python; then
  ( cd python
    pytest
    set +f
    pylint -- *.py
    mypy -- *.py
    set -f)
fi
