#!/usr/bin/env python

import sys
import math

def main(argv):
  if len(argv) not in (2, 3):
    sys.exit("Usage: %s NUM_PEOPLE [NUM_DAYS]" % argv[0])

  try:
    for number in argv[1:]:
      int(number)
  except (ValueError):
    sys.exit("Argument is not a number: %s" % str(number))

  (num_people, num_days) = (int(argv[1]), 365)
  if len(argv) == 3:
    num_days = int(argv[2])

  numerator = math.factorial(num_days) / math.factorial(num_days - num_people)
  denominator = num_days ** num_people
  chance_of_no_collision = 1.0 * numerator / denominator
  print 1 - chance_of_no_collision

if __name__ == "__main__":
  main(sys.argv)
