#!/usr/bin/python2.4
#
# Copyright 2010 Google Inc. All Rights Reserved.

"""Show the probability of a birthday paradox collision.

The probability of a birthday paradox collision happening is surprisingly high.
This program calculates the probability of a birthday collision between N
people, or the probability of a collision between N of M things.
"""

__author__ = "johntobin@google.com (John Tobin)"

import decimal
import sys


def Factorial(number):
  """Calculate the factorial of a number.

  Args:
    number: an integer.  It will be coerced to an integer using int(), so you
            can pass a string; if you pass a float, it will be rounded by int().

  Returns:
    The factorial of the argument.

  Raises:
    ValueError: the number argument could not be coerced to an integer.
  """

  number = int(number)
  factorial = 1
  while number > 1:
    factorial *= number
    number -= 1
  return factorial


def Birthday(num_days, num_people):
  """Calculate the probability of a birthday collision.

  Args:
    num_days: the number of days in the year
    num_people: the number of people

  Returns:
    A number between 0 and 1 giving the probability of a collision.
  """

  numerator = (decimal.Decimal(Factorial(num_days))
               / decimal.Decimal(Factorial(num_days - num_people)))
  denominator = decimal.Decimal(num_days) ** decimal.Decimal(num_people)
  probability_of_no_collision = numerator / denominator
  return 1 - probability_of_no_collision


def main(argv):
  if len(argv) not in (2, 3):
    sys.exit("Usage: %s NUM_PEOPLE [NUM_DAYS]" % argv[0])

  try:
    for number in argv[1:]:
      int(number)
  except ValueError:
    sys.exit("Argument is not a number: %s" % str(number))

  (num_people, num_days) = (int(argv[1]), 365)
  if len(argv) == 3:
    num_days = int(argv[2])

  print Birthday(num_days, num_people)

if __name__ == "__main__":
  main(sys.argv)
