#!/bin/bash

set -e -f -u -o pipefail

# Removing old versions of vim breaks running vim sessions, and sometimes the
# autocmds break badly enough that modified files can't be saved.  Disable
# removal of old versions of vim.
# Similarly for neovim and tmux.
HOMEBREW_NO_CLEANUP_FORMULAE=neovim,tmux,vim
export HOMEBREW_NO_CLEANUP_FORMULAE

brew update
brew outdated
# Separately upgrade formula and casks so I can force bottles.
# Sometimes a formula doesn't have a bottle and upgrading will fail, so we
# survive the failure and try again without forcing bottle.
brew upgrade --force-bottle --formula || true
sleep 2
brew upgrade --formula
sleep 2
brew upgrade --cask --greedy
sleep 2
brew cleanup
