#!/bin/bash

set -e -f -u -o pipefail

# Homebrew doesn't run as root.
if [[ "${USER}" == "root" ]]; then
  exit 0
fi
# Don't try to update if the user can't write to the install directory.
if [[ ! -w "$(brew --prefix)" ]]; then
  exit 0
fi
if is_x86_64; then
  # Skip the iMac, most packages aren't pre-built, and upgrading takes forever.
  exit 0
fi

# Disable removal of old versions neovim and tmux.
HOMEBREW_NO_CLEANUP_FORMULAE=neovim,tmux
export HOMEBREW_NO_CLEANUP_FORMULAE

brew update
brew outdated
# Separately upgrade formula and casks so I can force bottles.
# Sometimes a formula doesn't have a bottle and upgrading will fail, so we
# survive the failure and try again without forcing bottle.
brew upgrade --yes --force-bottle --formula || true
sleep 2
brew upgrade --yes --formula
sleep 2
brew upgrade --yes --cask --greedy
sleep 2
brew autoremove
sleep 2
brew autoremove
sleep 2
brew cleanup
sleep 2
brew doctor --quiet
