#!/bin/bash

set -e -f -u -o pipefail

# Update homebrew and list packages that are out of date.
PATH="/usr/local/bin:/usr/local/sbin:$PATH" 
export PATH
cd /usr/local/Homebrew
# Disable automatic git gc and run it manually to prevent output about
# automatically running it.
git config --local gc.auto 0
brew update > /dev/null
git gc --quiet
brew outdated
brew cask outdated
brew doctor | grep -v 'Your system is ready to brew.' || true
