#!/bin/bash

set -e -f -u -o pipefail

# Update homebrew and list packages that are out of date.

main() {
  # This is very spammy now so just discard the output entirely.
  brew update >& /dev/null
  brew outdated
  brew doctor | grep -v 'Your system is ready to brew.' || true
  local output
  output="$(brew leaves --installed-as-dependency)"
  if [[ -n "${output}" ]]; then
    printf "Auto-installed packages that can be removed:\n%s\n\n" "${output}"
    printf 'Note: brew autoremove might not remove them\n'
  fi
}

main "$@"
