#!/bin/bash

set -e -f -u -o pipefail

# Update homebrew and list packages that are out of date.

main() {
  # This is very spammy now so just discard the output entirely.
  brew update >& /dev/null
  brew outdated
  brew doctor | grep -v 'Your system is ready to brew.' || true
}

main "$@"
