#!/bin/bash

set -e -f -u -o pipefail

# Homebrew doesn't run as root.
if [[ "${USER}" == "root" ]]; then
  exit 0
fi
# Don't try to update if the user can't write to the install directory.
if [[ ! -w "$(brew --prefix)" ]]; then
  exit 0
fi

# Disable removal of old versions neovim and tmux.
HOMEBREW_NO_CLEANUP_FORMULAE=neovim,tmux
export HOMEBREW_NO_CLEANUP_FORMULAE

brew update
brew outdated
if is_x86_64; then
  # Upgrade everything at once, not worrying about bottles.  The imac is
  # unsupported by Homebrew, and bottles aren't always available.
  brew upgrade
else
  # Separately upgrade formula and casks so I can force bottles.
  # Sometimes a formula doesn't have a bottle and upgrading will fail, so we
  # survive the failure and try again without forcing bottle.
  brew upgrade --force-bottle --formula || true
  sleep 2
  brew upgrade --formula
  sleep 2
  brew upgrade --cask --greedy
fi
sleep 2
brew autoremove
sleep 2
brew cleanup
