#!/bin/bash

set -e -f -u -o pipefail

# Sleep between commands to reduce the chance of errors like:
# "Error: Another active Homebrew update process is already in progress."
brew() {
  command brew "$@"
  sleep 1
}

brew update
if [[ -n "$(brew outdated)" ]]; then
  # Fetch everything first to minimise the time that binaries are unavailable.
  # shellcheck disable=SC2046
  brew fetch --force-bottle $(brew outdated --formula)
  brew upgrade --force-bottle
fi
brew upgrade --cask
brew cleanup
