#!/bin/bash

set -e -f -u -o pipefail

PATH="${HOME}/bin:${PATH}"

# Check that git repos don't have any uncommitted or unpushed changes.
main() {
  local repo result=0
  for repo in "$@"; do
    if [[ ! -d "${repo}/.git" ]]; then
      continue
    fi
    if (cd "${repo}" && git transport-is-https); then
      continue
    fi
    if ! (cd "${repo}" && git check-local-copy-is-clean); then
      result=1
    fi
  done
  return "${result}"
}

main "$@"
