#!/bin/bash

set -e -f -u -o pipefail

# shellcheck disable=SC2207
processes=($(pgrep "Backup and Sync" || true))
if [[ "${#processes[@]}" -lt 3 ]]; then
  printf "%s: expecting >= 3 processes, found %s\\n" "$0" "${#processes[@]}"
  if [[ "${#processes[@]}" -gt 0 ]]; then
    ps -fp "${processes[@]}"
  fi
fi
