#!/bin/bash

set -e -f -u -o pipefail

check_single_rediect() {
  local expected_url="$1" check_url="$2" sleep_time="$3"
  for ((i = 0; i < 5; i++)); do
    # HTTP/1 uses "Location:", HTTP/2 uses "location:", so do a
    # case-insensitive check.
    if curl --silent --show-error --head "${check_url}" 2> /dev/null \
        | grep -i -q "^location: ${expected_url}"; then
      return 0
    fi
    sleep "${sleep_time}"
  done
  return 1
}

check_redirects() {
  local sleep_time="$1" expected_url="$2"
  shift 2
  local failures=0 url
  for url in "$@"; do
    if ! check_single_rediect "${expected_url}" "${url}" "${sleep_time}"; then
      failures=$((failures + 1))
      printf "Bad/missing redirect for %s, expected %s\\n" \
        "${url}" "${expected_url}"
      curl --head "${url}"
    fi
  done
  return "${failures}"
}

main() {
  if [[ ! -t 0 ]]; then
    sleep $((RANDOM % 600))
    sleep_time=30
  else
    sleep_time=1
  fi

  check_redirects \
    "${sleep_time}" \
    "https://www.arianetobin.ie" \
    "http://ariane.ie" \
    "https://ariane.ie" \
    "http://www.ariane.ie" \
    "https://www.ariane.ie" \
    \
    "http://arianetobin.ie" \
    "https://arianetobin.ie" \
    \
    "http://arianetobin.com" \
    "https://arianetobin.com" \
    "http://www.arianetobin.com" \
    "https://www.arianetobin.com" \
    \
    "http://metalatplay.com" \
    "https://metalatplay.com" \
    "http://www.metalatplay.com" \
    "https://www.metalatplay.com" \
    \
    "http://metalatwork.com" \
    "https://metalatwork.com" \
    "http://www.metalatwork.com" \
    "https://www.metalatwork.com" \
    \
    "http://nakedmetalsmith.com" \
    "https://nakedmetalsmith.com" \
    "http://www.nakedmetalsmith.com" \
    "https://www.nakedmetalsmith.com" \

  check_redirects \
    "${sleep_time}" \
    "https://dev.arianetobin.ie" \
    "http://dev.arianetobin.ie"

  check_redirects \
    "${sleep_time}" \
    "https://www.johntobin.ie" \
    "http://www.johntobin.ie" \
    "http://johntobin.ie" \
    "https://johntobin.ie"
}

main
