#!/bin/bash

set -e -f -u -o pipefail

if [[ -z "${CAFFEINATED:-}" ]]; then
  CAFFEINATED="do not sleep"
  export CAFFEINATED
  exec caffeinate -i "$0"
fi

# Deal with the special cases first.
# Ariane's website also needs to be updated in the right order.  Push any local
# changes first.
retry initial-ariane-theme -- check-git-repos "${HOME}/src/ariane-theme"
printf "\\n\\n\\nariane-theme\\n"
retry update-ariane-theme -- \
  ssh -o ControlMaster=no -t johntobin@hosting update-ariane-theme

# dotfiles and bin are the next most likely source of diffs, and they can be
# fixed mostly automatically.
printf "\\n\\n\\ndotfiles\\n"
run-everywhere update-dotfiles-and-bin
# Run a second time so that commits from later machines are pulled to earlier
# machines.
run-everywhere update-dotfiles-and-bin

# Now do the rest of the checks.
# shellcheck disable=SC2016
run-everywhere --users johntobin 'check-git-repos "${HOME}/bin" "${HOME}/src/"*'
