#!/bin/bash

set -e -f -u -o pipefail

check_single_host() {
  local host="$1"
  printf "\n\n\nProcessing %s\\n" "${host}"
  # shellcheck disable=SC2016
  retry --press_enter_before_retrying 10 "${host}" -- \
    ssh -o ControlMaster=no -t "johntobin@${host}" \
    'check-git-repos "${HOME}/bin" "${HOME}/src/"*'
}

if [[ -z "${CAFFEINATED:-}" ]]; then
  CAFFEINATED="do not sleep"
  export CAFFEINATED
  exec caffeinate -i "$0"
fi

# Deal with the special cases first.
# hugo-coder needs to be updated in the right order.
retry --press_enter_before_retrying 30 hugo -- update-hugo-coder
# Ariane's website also needs to be updated in the right order.  Push any local
# changes first.
retry --press_enter_before_retrying 30 initial-ariane-theme -- \
  check-git-repos "${HOME}/src/ariane-theme"
printf "\\n\\n\\nariane-theme\\n"
retry --press_enter_before_retrying 30 update-ariane-theme -- \
  ssh -o ControlMaster=no -t johntobin@hosting update-ariane-theme

# dotfiles and bin are the next most likely source of diffs, and they can be
# fixed mostly automatically.
printf "\\n\\n\\ndotfiles\\n"
run-everywhere update-dotfiles-and-bin
# Run a second time so that commits from later machines are pulled to earlier
# machines.
run-everywhere update-dotfiles-and-bin

# Now do the rest of the checks.
for host in laptop home hosting; do
  check_single_host "${host}"
done
