#!/bin/bash

set -e -u -f -o pipefail

# Initial setup won't have the right environment, so extend $PATH.
PATH="${HOME}/src/bin:/opt/homebrew/bin:/usr/local/bin:${PATH}"
export PATH

DESTDIR="${HOME}/src/dotfiles"
readonly DESTDIR
if [[ ! -d "${DESTDIR}" ]]; then
  mkdir -p "$(dirname "${DESTDIR}")"
  git clone https://github.com/tobinjt/dotfiles.git "${DESTDIR}"
fi
# Make .ssh inaccessible.
chmod 700 "${DESTDIR}/.ssh"
# Remove files that linkdirs will not overwrite.
rm -f "${HOME}/.bashrc" "${HOME}/.bash_logout" "${HOME}/.profile"
dotfiles
# Create some directories that'll be needed.
mkdir -p "${HOME}/tmp/generated" "${HOME}/.ssh/control"
if [[ "${USER}" == "johntobin" ]]; then
  sed -i -e 's!https://github.com/!git@github.com:!' .git/config
  # I need to do this anyway, so might as well do it now.
  sed -i -e 's!https://github.com/!git@github.com:!' \
    "${HOME}/src/bin/.git/config"
  (cd "${HOME}/src/bin" && install-pre-commit-hooks)
fi
