#!/bin/bash

set -e -u -f -o pipefail

# Initial setup won't have the right environment, so extend $PATH.
PATH="${HOME}/bin:/opt/homebrew/bin:/usr/local/bin:${PATH}"
export PATH

# Stop git looking for a commit message when 'git pull' is run.
GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT

DESTDIR="${HOME}/src/dotfiles"
readonly DESTDIR
if [[ ! -d "${DESTDIR}" ]]; then
  mkdir -p "$(dirname "${DESTDIR}")"
  git clone https://github.com/tobinjt/dotfiles.git "${DESTDIR}"
fi
cd "${DESTDIR}"
# Make .ssh inaccessible.
chmod 700 .ssh
git pull --no-rebase
git submodule init
git submodule update
# Remove files that linkdirs will not overwrite.
rm -f "${HOME}/.bashrc" "${HOME}/.bash_logout" "${HOME}/.profile"
dotfiles
if [[ "${USER}" == "johntobin" ]]; then
  sed -i -e 's!https://github.com/!git@github.com:!' .git/config
  # I need to do this anyway, so might as well do it now.
  sed -i -e 's!https://github.com/!git@github.com:!' "${HOME}/bin/.git/config"
  (cd "${HOME}/bin" && "${HOME}/bin/install-pre-commit-hooks")
fi
