#!/bin/bash

set -e -f -u -o pipefail

main() {
  if [[ "$#" != 0 ]]; then
    printf "Usage: %s\\n" "$0" >&2
    printf "You will be promoted for a SASL password\\n" >&2
    exit 1
  fi

  local sasl_file="/etc/postfix/sasl_passwd"
  local answer
  read -r -p "Delete ${sasl_file}? yes/no (default no): " answer
  if [[ "${answer}" == "yes" ]]; then
    printf "Deleting %s\n" "${sasl_file}"
    rm -f "${sasl_file}"
  else
    printf "NOT deleting %s\n" "${sasl_file}"
  fi

  if [[ ! -f "${sasl_file}" ]]; then
    local email password
    read -r -p "Enter gmail address: " email
    read -r -p "Enter SASL password: " password
    touch "${sasl_file}"
    chmod 600 "${sasl_file}"
    cat > "${sasl_file}" <<END_OF_SASL
[smtp.gmail.com]:587 ${email}:${password}
END_OF_SASL
    postmap hash:"${sasl_file}"
  fi

  cat > /etc/postfix/virtual <<END_OF_VIRTUAL
root johntobin@johntobin.ie
ariane johntobin@johntobin.ie
arianetobin johntobin@johntobin.ie
johntobin johntobin@johntobin.ie
END_OF_VIRTUAL
  postmap hash:/etc/postfix/virtual

  postconf compatibility_level=2
  postconf inet_protocols="ipv4"
  postconf relayhost="[smtp.gmail.com]:587"
  postconf smtp_sasl_auth_enable="yes"
  postconf smtp_sasl_mechanism_filter="plain"
  postconf smtp_sasl_password_maps="hash:/etc/postfix/sasl_passwd"
  postconf smtp_sasl_security_options="noanonymous"
  postconf smtp_tls_security_level="encrypt"
  postconf smtp_use_tls="yes"
  postconf virtual_alias_maps="hash:/etc/postfix/virtual"
  postfix reload || true

  mail -s "Testing mail from ${HOSTNAME}" johntobin@johntobin.ie <<END
Testing mail from ${HOSTNAME}
END
}

main "$@"
