#!/bin/bash

set -e -f -u -o pipefail

main() {
  if [[ "$#" != 0 ]]; then
    printf "Usage: %s\\n" "$0" >&2
    printf "You may be promoted for a SASL password\\n" >&2
    exit 1
  fi

  local sasl_file="/etc/postfix/sasl_passwd"
  if [[ ! -f "${sasl_file}" ]]; then
    local email password
    read -r -p "Enter gmail address: " email
    read -r -p "Enter SASL password (check ${sasl_file}): " password
    touch "${sasl_file}"
    chmod 600 "${sasl_file}"
    cat > "${sasl_file}" <<END_OF_SASL
[smtp.gmail.com]:587 ${email}:${password}
END_OF_SASL
  fi
  postmap hash:"${sasl_file}"

  cat > /etc/postfix/virtual <<END_OF_VIRTUAL
root johntobin@johntobin.ie
arianetobin johntobin@johntobin.ie
johntobin johntobin@johntobin.ie
END_OF_VIRTUAL
  postmap hash:/etc/postfix/virtual

  # Remove backwards-compatible settings.
  postconf -X smtp_use_tls
  postconf -X smtpd_use_tls

  postconf compatibility_level="3.6"
  postconf inet_interfaces="loopback-only"
  postconf inet_protocols="all"
  postconf mydestination="localhost.localdomain, localhost"
  postconf myhostname="arianetobin.ie"
  postconf relayhost="[smtp.gmail.com]:587"
  postconf smtp_sasl_auth_enable="yes"
  postconf smtp_sasl_password_maps="hash:/etc/postfix/sasl_passwd"
  postconf smtp_sasl_security_options="noanonymous"
  postconf smtp_tls_security_level="encrypt"
  postconf smtp_tls_mandatory_ciphers="high"
  postconf virtual_alias_maps="hash:/etc/postfix/virtual"
  # Cargo culting these settings from old hosting.
  postconf default_transport="smtp"
  postconf relay_transport="relay"

  postfix reload
}

main "$@"
