#!/bin/bash

set -e -f -u -o pipefail

# Cleanup Adobe logs.
dir="${HOME}/Library/Logs/"
if [[ -d "${dir}" ]]; then
  (cd "${dir}" \
    && set +f \
    && rm -f PDApp*20*.log \
    && rm -f NGLClient_default*20*.log \
    && rm -f oobelib*20*.log \
  )
fi

dir_list=()
# Cleanup Plex updates.
dir_list+=("${HOME}/Library/Application Support/Plex Media Server/Updates")
# Some random Apple thing that leaves lots of logs around.
dir_list+=("${HOME}/Library/Caches/com.apple.nsurlsessiond/Downloads")
for dir in "${dir_list[@]}"; do
  if [[ -d "${dir}" ]]; then
    tmpreaper --mtime 7d "${dir}"
  fi
done

# Clean up vim leftovers.
tmpreaper --mtime 28d "${HOME}/tmp/vim"
