#!/bin/bash

set -e -f -u -o pipefail

echo '<html>'
echo '  <head>'
echo "    <title>${PWD} $*</title>"
echo '  </head>'
echo '  <body>'

command ls "$@" \
  | sed -e 's/\.[^.]*$//' \
        -e 's/ S[0-9]\{1,2\}$//' \
        -e 's/ Season [0-9]\{1,2\}$//' \
        -e 'h' \
        -e 's/ /+/g' \
        -e 's,^,<a href="http://www.imdb.com/find?q=,' \
        -e 's,$,">,' \
        -e 'G' \
        -e 's/\n//' \
        -e 's,$,</a> <br/>,' \
        -e 's/^/    /' \
  | uniq

echo '  </body>'
echo '</html>'
