#!/bin/sh

set -e

echo '<html>'
echo '  <head>'
echo "    <title>${PWD} $@</title>"
echo '  </head>'
echo '  <body>'

ls "$@" \
  | sed -e 's/\.[^.]*$//' \
        -e 'h' \
        -e 's/ /+/g' \
        -e 's,^,<a href="http://www.imdb.com/find?q=,' \
        -e 's,$,">,' \
        -e 'G' \
        -e 's/\n//' \
        -e 's,$,</a> <br/>,' \
        -e 's/^/    /'

echo '  </body>'
echo '</html>'
