#!/bin/bash

set -e -f -u -o pipefail

# This is duplicated in ~/src/dotfiles/.dotfiles.d/10-ssh-config.sh.
dotfiles_sources() {
  find "${HOME}/src" -maxdepth 1 -iname '*dotfiles*' -type d
}

list_config_snippets() {
  local config_snippets_dir="$1"
  find "${config_snippets_dir}" -type f -perm -0100 -print | sort
}

main() {
  local IGNORE_FILENAME=".dotfiles.ignore"
  readonly IGNORE_FILENAME
  local flags=("--ignore_symlinks") later_flags=()
  local return_early=0 run_config_snippets=1 opt
  while getopts ":dfhnrRX" opt "$@"; do
    case "${opt}" in
      d)
        flags+=("--dryrun")
        return_early=1
        ;;
      f)
        flags+=("--force")
        ;;
      h)
        cat <<END_OF_HELP
Usage: $0 [-d] [-f] [-n] [-r] [-R] [-X]
Links files in ${HOME}/src/*dotfiles* to ${HOME}
Files and directories listed in ${HOME}/src/*dotfiles*/${IGNORE_FILENAME} will
be ignored.  Note: ${IGNORE_FILENAME} lists are global, not scoped to the
directory containing them.

Options:
  -f: force overwrite of files that differ.
  -d: dry run, overrides -f.
  -n: do not run config snippets.
  -r: report unexpected files in destination.
  -R: report unexpected directories in destination.
  -X: delete unexpected files in destination.
END_OF_HELP
        exit 0
        ;;
      n)
        run_config_snippets=0
        ;;
      r)
        flags+=("--report_unexpected_files" "--ignore_unexpected_children")
        return_early=1
        ;;
      R)
        flags+=("--report_unexpected_files")
        later_flags+=("--no-ignore_unexpected_children")
        return_early=1
        ;;
      X)
        flags+=("--delete_unexpected_files" "--ignore_unexpected_children")
        ;;
      *)
        echo "Unrecognised flag: ${OPTARG}" >&2
        exit 1
    esac
  done

  local SKIP_FILES=() SOURCE_DIRS=() dir
  for dir in $(dotfiles_sources); do
    SOURCE_DIRS+=("${dir}")
    if [[ -f "${dir}/${IGNORE_FILENAME}" ]]; then
      SKIP_FILES+=("--ignore_file=${dir}/${IGNORE_FILENAME}")
    fi
  done
  readonly SKIP_FILES SOURCE_DIRS

  linkdirs \
    "${SKIP_FILES[@]:+${SKIP_FILES[@]}}" \
    "${flags[@]:+${flags[@]}}" \
    "${later_flags[@]:+${later_flags[@]}}" \
    "${SOURCE_DIRS[@]}" \
    "${HOME}"
  if [[ "${return_early}" -eq 1 ]]; then
    return
  fi

  if [[ "${run_config_snippets}" -eq 0 ]]; then
    return
  fi
  local snippet
  for snippet in $(list_config_snippets "${HOME}/.dotfiles.d"); do
    if ! "${snippet}"; then
      printf "Failed running %s\n" "${snippet}" >&2
      exit 1
    fi
  done
}

main "$@"
