#!/usr/bin/env perl

# $Id$

use strict;
use warnings;

use Storable;
use Data::Dumper;

if (@ARGV != 1) {
    die qq{Usage: $0 /path/to/.ikiwiki/indexdb\n};
}

$Data::Dumper::Sortkeys = 1;
print Dumper(retrieve(@ARGV));
