#!/bin/bash

set -e -f -u -o pipefail

main() {
  if [[ "$#" -ne 0 ]]; then
    printf "Usage: %s\\nNo arguments accepted.\\n" "$0" >&2
    return 1
  fi

  # Check for uncommitted changes.
  local output result=0
  output="$(git status --short)"
  if [[ -n "${output}" ]]; then
    # Use human readable git status because it's more familiar.
    printf "Uncommitted changes\\n" >&2
    git status >&2
    result=1
  fi

  # Check for unpushed commits.
  if ! git symbolic-ref HEAD >& /dev/null; then
    # No upstream, so don't check that.
    return "${result}"
  fi
  output="$(git log "@{u}..")"
  if [[ -n "${output}" ]]; then
    printf "Unpushed commits\\n%s\\n" "${output}" >&2
    result=1
  fi
  return "${result}"
}

main "$@"
