#!/bin/bash

set -e -f -u -o pipefail

filename="$(mktemp -t gocov.XXXXXXXXXXXX)"
go test --coverprofile="${filename}" --covermode=count
go tool cover --func="${filename}" | grep -v -e '100.0%$' -e '-main.go:'
if [[ -z "${NO_BROWSER:-}" ]]; then
  go tool cover --html="${filename}"
fi
rm -f "${filename}"
