#!/bin/bash

set -e -u -o pipefail

# Coverage runs tests, so there's no need to run them separately.
filename="$(mktemp -t gocov.XXXXXXXXXXXX)"
# I want ${filename} to be expanded now, because when we exit
# successfully it will be out of scope and cannot be expanded.
# shellcheck disable=SC2064
trap "rm -f \"${filename}\"" EXIT

go test --coverprofile="${filename}" --covermode=set
if go tool cover --func="${filename}" \
    | grep -v -w \
        -e '100.0%$' \
        -e '^total:' \
        -e 'main' \
        -e 'projectEuler[[:digit:]_]\+' \
        -e 'aoc[[:digit:]]\{4\}_[[:digit:]]\+' \
        ; then
  exit 1
fi
