#!/bin/bash

set -e -f -u -o pipefail

# Run mypy when inputs change.
if [[ "$#" -eq 0 ]]; then
  set +f
  files=(./*.py)
  set -f
else
  files=("$@")
fi
inotify_wrapper "${files[@]}" -- mypy -- "${files[@]}"
