#!/bin/bash

# Installs development tools that aren't packaged by Homebrew or Debian.

set -e -f -u -o pipefail

if is_mac_os && type brew >& /dev/null; then
  brew-update-brew-cleanup
fi

# If you run 'go get' from a directory containing go source code it will change
# go.{mod,sum} in that directory, so change to a temporary directory.
cd "${TMPDIR:-/tmp}"
if type go >& /dev/null && [[ -d "${GOPATH}" ]]; then
  # Clean up binaries so that GoInstallBinaries will install updated binaries.
  bindir="${GOPATH}/bin"
  if [[ -d "${bindir}" ]]; then
    printf "Clearing out binaries from %s\\n" "${bindir}"
    find "${bindir}" -type f -delete
  fi

  # keep-sorted start
  # Check code coverage.
  go install github.com/tobinjt/golang-coverage-check@latest
  # Dead code detection.
  go install golang.org/x/tools/cmd/deadcode@latest
  # Auto-import packages.
  go install golang.org/x/tools/cmd/goimports@master
  # keep-sorted end
fi

if [[ -d "${HOME}/.cargo" ]]; then
  if ! type rustup >& /dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
      | sh -s -- --no-modify-path
  fi
  # Add ~/.cargo/bin to $PATH.
  source "${HOME}/.shellrc"
  rustup install stable
  rustup update
  rustup toolchain install
  rustup component add clippy rust-analyzer rust-src
  # https://crates.io/crates/cargo-binstall
  (unset RUSTC_WRAPPER; cargo install --locked cargo-binstall)
  # https://crates.io/crates/sccache
  (unset RUSTC_WRAPPER; cargo binstall --locked --no-confirm sccache)
  # https://github.com/taiki-e/cargo-llvm-cov?tab=readme-ov-file#from-source
  cargo +stable binstall --locked --no-confirm cargo-llvm-cov

  # keep-sorted start
  # https://crates.io/crates/cargo-audit
  cargo binstall --locked --no-confirm cargo-audit
  # https://crates.io/crates/cargo-binutils
  cargo binstall --locked --no-confirm cargo-binutils
  # https://github.com/dtolnay/cargo-edit
  cargo binstall --locked --no-confirm cargo-edit
  # https://github.com/dtolnay/cargo-expand
  cargo binstall --locked --no-confirm cargo-expand
  # https://crates.io/crates/cargo-mutants
  cargo binstall --locked --no-confirm cargo-mutants
  # https://nexte.st/docs/installation/from-source/
  cargo binstall --locked --no-confirm cargo-nextest
  # https://crates.io/crates/cargo-release
  cargo binstall --locked --no-confirm cargo-release
  # https://crates.io/crates/cargo-watch
  cargo binstall --locked --no-confirm cargo-watch
  # keep-sorted end

  # Tooling I wrote :)
  cargo install colx
  cargo install path-parents
  cargo install wrap-command
fi

if [[ -d "${HOME}/tmp/bin/node_modules" ]]; then
  # Update existing packages first.
  npm update -g
  # Lint for CSS.
  npm install -g csslint
  # Google Apps Script.  https://github.com/google/clasp
  npm install -g @google/clasp
  npm install -g typescript
fi
