#!/bin/bash

set -e -f -u -o pipefail

bubc

# If you run 'go get' from a directory containing go source code it will change
# go.{mod,sum} in that directory, so change to a temporary directory.
cd "${TMPDIR}"
if type go >& /dev/null; then
  # Clean up binaries so that GoInstallBinaries will install updated binaries.
  bindir="${GOPATH}/bin"
  if [[ -d "${bindir}" ]]; then
    printf "Clearing out binaries from %s\\n" "${bindir}"
    find "${bindir}" -type f -delete
  fi
  # Binaries needed by vim-go; use GoInstallBinaries because GoUpdateBinaries
  # would install second copies of homebrew binaries; all the existing binaries
  # have been deleted so fresh binaries will be built.
  vim -c 'execute ":GoInstallBinaries" | :quit'

  # Tools used by Syntastic; some of the tools are installed by GoUpdateBinaries
  # so I don't need to install them a second time.
  go install golang.org/x/tools/cmd/gotype@latest

  # Vulnerability checking.
  go install golang.org/x/vuln/cmd/govulncheck@latest

  # Dead code detection.
  go install golang.org/x/tools/cmd/deadcode@latest

  if type codesign >& /dev/null; then
    # Debugger; installed by vim-go, manual instructions at
    # https://github.com/go-delve/delve/blob/master/Documentation/installation/README.md
    # Enable developer mode to avoid repeated password prompts.
    printf "Enabling developer mode; sudo might ask for a password\n"
    sudo /usr/sbin/DevToolsSecurity -enable

    # Needs to be signed to avoid repeated password prompts.
    # Docs for signing are https://sourceware.org/gdb/wiki/PermissionsDarwin
    readonly signing_cert="gdb-cert"
    if ! security find-certificate -Z -p -c "${signing_cert}" \
        /Library/Keychains/System.keychain > /dev/null 2>&1; then
      # Cert is missing, most likely this is a newly setup machine, create it.
      cert_config="$(mktemp /tmp/code-signing.cert_config.XXXXXXXXXX)"
      readonly cert_config
      cat > "${cert_config}" <<CERT_CONFIG
[ req ]
default_bits       = 2048        # RSA key size
encrypt_key        = no          # Protect private key
default_md         = sha512      # MD to use
prompt             = no          # Prompt for DN
distinguished_name = codesign_dn # DN template
[ codesign_dn ]
commonName         = "${signing_cert}"
[ codesign_reqext ]
keyUsage           = critical,digitalSignature
extendedKeyUsage   = critical,codeSigning
CERT_CONFIG

      new_cert="$(mktemp /tmp/code-signing.new_cert.XXXXXXXXXX)"
      new_key="$(mktemp /tmp/code-signing.new_key.XXXXXXXXXX)"
      readonly new_cert new_key
      openssl req -new -newkey rsa:2048 -x509 -days 3650 -nodes \
        -config "${cert_config}" -extensions codesign_reqext -batch \
        -out "${new_cert}" -keyout "${new_key}"

      printf "Configuring code signing cert, sudo may ask for a password\n"
      old_rights="$(mktemp /tmp/code-signing.old_rights.XXXXXXXXXX)"
      readonly old_rights
      # shellcheck disable=SC2024
      sudo security authorizationdb read com.apple.trust-settings.admin \
        > "${old_rights}"
      sudo security authorizationdb write com.apple.trust-settings.admin allow
      sudo security add-trusted-cert -d -r trustRoot -p codeSign \
        -k /Library/Keychains/System.keychain "${new_cert}"
      # shellcheck disable=SC2024
      sudo security authorizationdb write com.apple.trust-settings.admin \
        < "${old_rights}"
      sudo security import "${new_key}" -A -k /Library/Keychains/System.keychain
    fi

    xml="$(mktemp /tmp/code-signing.xml.XXXXXXXXXX)"
    readonly xml
    cat > "${xml}" <<SIGNING
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.debugger</key>
    <true/>
</dict>
</plist>
</pre>
SIGNING

    # Can't run this over SSH :(
    if [[ -z "${SSH_CONNECTION:-}" ]]; then
      codesign --entitlements "${xml}" -fs "${signing_cert}" "$(type -P dlv)"
    fi
  fi
fi

if type rustup >& /dev/null; then
  rustup update
  rustup component add clippy rust-analyzer rust-src
  rustup update
  # https://github.com/taiki-e/cargo-llvm-cov?tab=readme-ov-file#from-source
  cargo +stable install cargo-llvm-cov --locked
  # TODO: I might need to sign binaries so I can debug.
fi
