#!/bin/bash

set -e -f -u -o pipefail

if type go >& /dev/null; then
  # Clean up old stuff; occasionally installation has problems because of
  # previous layouts or something, so clean up first.
  # Go makes everything readonly for some reason so fix directory permissions to
  # enable deletion.
  dirs=(bin pkg)
  (printf "Clearing out %s\\n" "${GOPATH}" \
    && mkdir -p "${GOPATH}" \
    && cd "${GOPATH}" \
    && mkdir -p "${dirs[@]}" \
    && find "${dirs[@]}" -type d -print0 | xargs -0 chmod 755 \
    && rm -rf "${dirs[@]}")
  # Binaries needed by vim-go.
  vim -c 'execute ":GoUpdateBinaries" | :quit'

  # Tools used by Syntastic; some of the tools are installed by GoUpdateBinaries
  # so I don't need to install them a second time.
  go get -u golang.org/x/tools/cmd/gotype

  # Debugger; installed by vim-go, manual instructions at
  # https://github.com/go-delve/delve/blob/master/Documentation/installation/osx/install.md
  # Needs to be signed to avoid repeated password prompts.
  # I manually followed the steps to create the cert in
  # https://sourceware.org/gdb/wiki/PermissionsDarwin
  xml="$(mktemp /tmp/code-signing.XXXXXXXXXX)"
  cat > "${xml}" <<SIGNING
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.debugger</key>
    <true/>
</dict>
</plist>
</pre>
SIGNING
  codesign --entitlements "${xml}" -fs gdb-cert "$(type -P dlv)"
  rm "${xml}"
fi
