#!/bin/bash

# Installs development tools that aren't packaged by Homebrew or Debian.

set -e -f -u -o pipefail

if is_mac_os && type brew >& /dev/null; then
  brew-update-brew-cleanup
fi

# If you run 'go get' from a directory containing go source code it will change
# go.{mod,sum} in that directory, so change to a temporary directory.
cd "${TMPDIR:-/tmp}"
if type go >& /dev/null; then
  # Clean up binaries so that GoInstallBinaries will install updated binaries.
  bindir="${GOPATH}/bin"
  if [[ -d "${bindir}" ]]; then
    printf "Clearing out binaries from %s\\n" "${bindir}"
    find "${bindir}" -type f -delete
  fi

  # keep-sorted start
  # Dead code detection.
  go install golang.org/x/tools/cmd/deadcode@latest
  # Auto-import packages.
  go install golang.org/x/tools/cmd/goimports@master
  # keep-sorted end
fi

if type rustup >& /dev/null; then
  # Used with Homebrew Rust but not on Debian?
  if type rustup-init >& /dev/null; then
    rustup-init --no-modify-path -y
  fi
  # Add ~/.cargo/bin to $PATH.
  source "${HOME}/.shellrc"
  rustup install stable
  rustup update
  rustup toolchain install
  rustup component add clippy rust-analyzer rust-src
  # https://github.com/taiki-e/cargo-llvm-cov?tab=readme-ov-file#from-source
  cargo +stable install --locked cargo-llvm-cov
  # https://crates.io/crates/cargo-binutils
  cargo install --locked cargo-binutils
  # https://github.com/dtolnay/cargo-expand
  cargo install --locked cargo-expand
  # https://crates.io/crates/cargo-mutants
  cargo install --locked cargo-mutants
  # https://nexte.st/docs/installation/from-source/
  cargo install --locked cargo-nextest
  # https://crates.io/crates/cargo-outdated
  cargo install --locked cargo-outdated
  # https://crates.io/crates/cargo-watch
  cargo install --locked cargo-watch
  # Tooling I wrote :)
  cargo install colx
  cargo install path-parents
fi

if [[ -d "${HOME}/tmp/bin/node_modules" ]]; then
  # Update existing packages first.
  npm update -g
  # Lint for CSS.
  npm install -g csslint
  # Google Apps Script.  https://github.com/google/clasp
  npm install -g @google/clasp
  npm install -g typescript
fi
