#!/bin/bash

set -e -f -u -o pipefail

# Run pytest when inputs change.
set +f
if [[ "$#" -eq 0 ]]; then
  files=(*.py)
else
  files=("$@")
fi
inotify_wrapper "${files[@]}" -- pytest -- "${files[@]}"
