#!/bin/bash

set -e -f -u -o pipefail

# Kill Zoom processes that have been running for more than 3 hours, that is the
# longest I can imagine myself using Zoom for.

main() {
  # ps output looks like:
  #   15322    03:17:52 /Applications/zoom.us.app/Contents/MacOS/zoom.us
  #   15786       09:01 /Applications/zoom.us.app/Contents/Frameworks/caphost.app/Contents/MacOS/caphost
  # If $2 matches :.: it's hours:minutes:seconds rather than minutes:seconds.
  ps -u "${USER}" -x -o pid,etime,comm \
    | (grep /Applications/zoom.us.app || true) \
    | awk '$2 ~ /:.*:/ {
             sub(":.*", "", $2);
             sub("^0", "", $2);
             if ($2 >= 2) {
               print $1;
             }
           }' \
    | xargs echo kill -9
}

main "$@"
