#!/bin/bash

set -e -f -u -o pipefail

destdir="$(mktemp -d -t linkchecker-cron.XXXXXXXXXX)"
cd "${destdir}"

if [[ ! -t 0 ]]; then
  sleep $((RANDOM % 600))
fi

# - Cut down on output so this can be run from cron, but write to a file that
#   can be displayed on failure or when run interactively.
# - Check external links but do not recurse on external sites.
# - Exclude domains that definitely won't work; list was determined through
#   debugging and perserverence.
# - stderr will always have a warning about SSL certificates.
# - To figure out problems run with '--debug=checking' and look for the URLs
#   that keep getting checked at the end.
exit_status=0
linkchecker \
  --no-status \
  --quiet \
  --file-output=text \
  --check-extern \
  --no-follow-url='!(www.johntobin.ie|www.arianetobin.ie)' \
  --ignore-url=//www.example.org \
  --ignore-url=//pool.ntp.org \
  "$@" >stdout 2>stderr || exit_status="$?"

if [[ "${exit_status}" != 0 || -t 0 ]]; then
  printf "Output in %s\\n" "${destdir}"
  set +f
  cat -- *
  set -f
else
  rm -rf "${destdir}"
fi
exit "${exit_status}"
