#!/usr/bin/env perl

# $Id$

use strict;
use warnings;
use File::Spec::Functions qw(splitpath catpath rootdir canonpath);

my (@options);
OPTION:
while (my $option = shift @ARGV) {
    if ($option eq q{--}) {
        last OPTION;
    }
    push @options, $option;
}

if (not @ARGV) {
    die qq{Usage: $0 [LS OPTIONS] -- TARGET [TARGETS]\n};
}
# trailing slashes confuse File::Spec
my @stack = map { canonpath($_) } reverse @ARGV;
my $rootdir = rootdir();

while (@stack) {
    my $target = pop @stack;
    system q{ls}, @options, $target;
    my ($volume, $dir, $file) = splitpath($target);
    $dir = canonpath($dir);
    if (length $dir and $dir ne $rootdir) {
        push @stack, catpath($volume, $dir);
    }
}
