#!/usr/bin/perl

use strict;
use warnings;

use feature qw(say);

use File::Spec::Functions;

my @banned_words = qw();
my %banned_words = map { ($_ => 1, qq{($_)} => 1) } @banned_words;
my %new_filenames;
foreach my $filename (glob q{*}) {
    my ($name) = ($filename);

    # Remove [stuff in square brackets]
    $name =~ s/\[[^]]*\]/ /g;
    # Remove (stuff in parentheses)
    $name =~ s/\([^)]*\)/ /g;
    # Substitute "&" with "and"
    $name =~ s/&/and/g;
    # mangle each word, discarding words we don't want.
    my @words = map { ucfirst }
                    map { s/^(?:part|cd)([123])$/p$1/; $_; }
                        grep { not exists $banned_words{$_} }
                            grep { not m/^20[01][0-9]$/ }
                                grep { length }
                                    split /[ ._]+/,
                                        lc $name;

    my $newname = join q{ }, @words;
    next if $newname eq $filename;

    if ($newname =~ s, - | -|- ,/,) {
        my $subdir = $newname;
        $subdir =~ s,/.*,,;
        if (not -d $subdir) {
            if (not mkdir $subdir) {
                warn qq{mkdir $subdir failed: $!\n};
                next;
            }
        }
    }

    if ($new_filenames{$newname}++) {
        warn qq{Already used: $filename -> $newname\n};
        next;
    }
    if (-e $newname) {
        if (lc $newname ne lc $filename) {
            warn qq{Already exists: $filename -> $newname\n};
            next;
        }
    }

    # Work around Windows' case-insensitivity
    my $temp_newname = $newname . q{X};
    say qq{$filename -> $temp_newname -> $newname};
    if ($new_filenames{$temp_newname}++) {
        warn qq{Already used: $filename -> $temp_newname\n};
        next;
    }
    if (-e $temp_newname) {
        warn qq{Already exists: $filename -> $temp_newname\n};
        next;
    }
    rename $filename, $temp_newname
        or die qq{$0: failed renaming $filename -> $temp_newname: $!\n};
    rename $temp_newname, $newname
        or die qq{$0: failed renaming $temp_newname -> $newname: $!\n};
}
