#!/usr/bin/env python3
"""Sort inputs naturally."""

import fileinput
import re
import sys

from collections.abc import Sequence

__author__ = "johntobin@johntobin.ie (John Tobin)"


def make_natural_sort_key(something: str) -> list[str | float]:
    """Create a list of keys to use when sorting."""
    fields = re.split(r"(\d+(?:.\d+)?)", something)
    converted_fields: list[str | float] = []
    for field in fields:
        try:
            converted_fields.append(float(field))
        except ValueError:
            converted_fields.append(field)
    return converted_fields


def main(argv: Sequence[str]):
    for entry in sorted(fileinput.input(argv), key=make_natural_sort_key):
        print(entry, end="")


if __name__ == "__main__":
    main(sys.argv[1:])
