#!/usr/bin/env python
#
# Copyright 2011 John Tobin.
# pylint: disable-msg=C6301,C6304

"""Sort inputs naturally."""

import fileinput
import re
import sys

__author__ = 'johntobin@johntobin.ie (John Tobin)'


def MakeNaturalSortKey(something):
  fields = re.split(r'(\d+(?:.\d+)?)', something)
  converted_fields = []
  for field in fields:
    try:
      converted_fields.append(float(field))
    except ValueError:
      converted_fields.append(field)
  return converted_fields


def main(argv):
  for entry in sorted(fileinput.input(argv), key=MakeNaturalSortKey):
    print entry,

if __name__ == '__main__':
  main(sys.argv[1:])
