#!/bin/bash

set -e -f -u -o pipefail

if [[ "$#" = 0 ]]; then
    cat <<USAGE >&2
Usage: $0 [-i] PATTERN [FILENAMES]
E.g.: $0 moon; $0 ^OPTIONS a-man-page
Print paragraphs starting with a line containing PATTERN and finishing with a
blank line.  Forward slashes in PATTERN need to be escaped.
-i switches to case-insensitive pattern matching.
USAGE
fi

case_flag=""
if [[ "$1" == "-i" ]]; then
  case_flag="I"
  shift
fi
pattern="$1"; shift
exec sed -n -e "/${pattern}/${case_flag},/^\$/p" "$@"
