#!/bin/bash

set -e -f -u -o pipefail
usage() {
  cat <<USAGE
Usage: $0 [-s N] [PATH PATH . . .]
Usage: $0 -h
If no filenames are provided reads from stdin.
Args:
  -h: Show usage message.
  -s N: Skip output of paths with N or fewer components (/bin has 1 component),
        /bin/test has 2 components.
USAGE
}
warn() {
  echo "$@" >&2
}
die() {
  warn "$@"
  exit 1
}

main() {
  SKIP=0
  while getopts hs: flag; do
    case "${flag}" in
      h)
        usage
        exit 0
        ;;
      s)
        SKIP="${OPTARG}"
        if ! grep -q '^[[:digit:]]\+$' <<< "${SKIP}" > /dev/null; then
          die "Bad argument '${SKIP}'; argument to -s must be an integer."
        fi
        ;;
      ?)
        die "$(usage)"
        ;;
    esac
  done
  shift $(( OPTIND - 1 ))
  readonly SKIP


  if [[ "$#" -eq 0 ]]; then
    if [[ -t 0 ]]; then
      warn "Refusing to read from terminal."
      warn ""
      die "$(usage)"
    fi
    cat
  else
    echo "$@"
  fi \
    | fmt -1 \
    | awk -v SKIP="${SKIP}" -f "${HOME}/bin/path-parents.awk"
}

# Only run main if being executed directly; do nothing if sourced for testing.
# Use basename so that it can be run as 'bash -x ./program ...'.
if [[ "$(basename "${BASH_SOURCE[0]}")" == "$(basename "${0}")" ]]; then
  main "$@"
fi
