#!/bin/bash

set -e -f -u -o pipefail

cd /etc
git check-local-copy-is-clean

# These arguments are necessary when a cert needs to be renewed.
certbot renew \
  --quiet \
  --pre-hook "service apache2 stop" \
  --post-hook "service apache2 start" \
  --standalone

if ! git check-local-copy-is-clean 2>/dev/null; then
  etckeeper commit 'Renew some certs.'
fi

sleep 5
curl --head --silent https://www.arianetobin.ie/ > /dev/null
