#!/bin/bash

set -e -f -u -o pipefail

main() {
  local APP="/Applications/Google Drive File Stream.app"
  local DEST="drive-file-stream.restart.plist"
  local LABEL="DriveFileStream.restart"
  local SLEEP_BETWEEN_ATTEMPTS="15"

  if [[ "$#" -eq 0 ]]; then
    main help
  else
    restart-app-automatically "${DEST}" "${APP}" "${LABEL}" \
      "${SLEEP_BETWEEN_ATTEMPTS}" "$@"
  fi
}

main "$@"
