#!/bin/bash

set -e -f -u -o pipefail

main() {
  local APP="/Applications/Moom.app/Contents/MacOS/Moom"
  local DEST="moom.restart.plist"
  local LABEL="Moom.restart"

  if [[ "$#" -eq 0 ]]; then
    main help
  else
    restart-app-automatically "${DEST}" "${APP}" "${LABEL}" "$@"
  fi
}

main "$@"
