#!/bin/bash

set -e -f -u -o pipefail

main() {
  local APP="/Applications/Backup and Sync.app/Contents/MacOS/Backup and Sync"
  local DEST="backup-and-sync.restart.plist"
  local LABEL="BackupAndSync.restart"

  if [[ "$#" -eq 0 ]]; then
    main help
  else
    restart-app-automatically "${DEST}" "${APP}" "${LABEL}" "$@"
  fi
}

main "$@"
