#!/bin/bash

set -e -f -u -o pipefail

output_plist() {
  local dest="$1" app="$2" label="$3"
  # Set up launchd to automatically restart the app when it exits.
  cat > "${dest}" <<END_OF_PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>RunAtLoad</key> <true/>  
        <key>KeepAlive</key> <true/>
        <key>Label</key> <string>${label}</string>
        <key>ProgramArguments</key>
        <array>
                <string>${app}</string>
        </array>
</dict>
</plist>
END_OF_PLIST
}

main() {
  local APP="/Applications/Pauses.app/Contents/MacOS/Pauses"
  local DEST="${HOME}/Library/LaunchAgents/pauses.restart.plist"
  local LABEL="Pauses.restart"
  if ! launchctl list | grep -q "${LABEL}"; then
    output_plist "${DEST}" "${APP}" "${LABEL}"
    launchctl load "${DEST}"
  fi
}

main
