#!/bin/bash

set -e -f -u -o pipefail

main() {
  local APP="/Applications/Pauses.app/Contents/MacOS/Pauses"
  local DEST="pauses.restart.plist"
  local LABEL="Pauses.restart"

  if [[ "$#" -ne 1 ]]; then
    main start
  else
    restart-app-automatically "${DEST}" "${APP}" "${LABEL}" "$@"
  fi
}

main "$@"
