#!/bin/bash

set -e -f -u -o pipefail

usage() {
  cat >&2 <<END_OF_USAGE
Usage: $0 SLEEP_TIME MESSAGE COMMAND [COMMAND_ARGS]

SLEEP_TIME: number of seconds to sleep between retries.
MESSAGE: message to display between retries.
COMMAND: The command to run.
COMMAND_ARGS: Arguments to be passed to COMMAND.
END_OF_USAGE
  exit "$1"
}

retry() {
  local sleep_time="$1" message="$2"
  shift 2
  until "$@"; do
    printf "Retrying %s\\n" "${message}"
    sleep "${sleep_time}"
  done
}

if [[ "$#" -lt 3 ]]; then
  usage 1
fi
retry "$@"
