#!/bin/bash

set -e -f -u -o pipefail

# Stop TmuxSetWindowName loading: it's not useful and it doesn't work properly
# when tmux is focused on a different pane.
nvim --headless \
  --cmd 'let g:loaded_TmuxSetWindowName=1' \
  -c "$@" -c "qa" > /dev/null
