#!/bin/bash

set -e -f -u -o pipefail

# Run a command if it exists, exit successfully if it doesn't.

if [[ "$#" -eq 0 ]]; then
  printf "Usage: %s command [arguments...]\n" "$0" >&2
  exit 1
fi
if type "$1" >& /dev/null; then
  "$@"
fi
