#!/bin/bash

# Run a command and send a mail if the command fails or produces output.
# Redirects stdout and stderr, so if your command or caller does that it won't
# work properly.

set -e -f -u -o pipefail

DESTINATION="$1"
shift
OUTPUT_FILE="$(mktemp -t OUTPUT_FILE.XXXXXXXXXXXXXXXX)"
trap 'rm -f "${OUTPUT_FILE}"' EXIT
readonly DESTINATION OUTPUT_FILE

EXIT_STATUS=0
"$@" > "${OUTPUT_FILE}" 2>&1 || EXIT_STATUS="$?"

if [[ "${EXIT_STATUS}" -ne 0 || -s "${OUTPUT_FILE}" ]]; then
  (printf "Exit status: %s\\nOutput:\\n" "${EXIT_STATUS}";
    cat "${OUTPUT_FILE}"
  ) | mail -s "${USER}@${HOSTNAME}: $*" "${DESTINATION}"
fi
exit "${EXIT_STATUS}"
