#!/usr/bin/env perl

use strict;
use warnings;

use Math::BigFloat;
use Regexp::Common;

my %suffixes = (
  k => 1024,
  m => 1024 ** 2,
  g => 1024 ** 3,
  t => 1024 ** 4,
  p => 1024 ** 5,
);

my $suffix_re = join q{}, q{[}, keys %suffixes, q{]};
$suffix_re = qr/(?:$suffix_re(?:b?)|e\+\d+)/i;

sub un_format_bytes {
  my ($number, $suffix) = @_;

  my ($big_number) = Math::BigFloat->new($number);
  $suffix =~ s/b$//i;
  $suffix = lc $suffix;
  return $big_number * $suffixes{$suffix};
}

sub un_format_scientific {
  my ($number, $suffix) = @_;

  $suffix =~ s/^e\+//i;
  my ($big_number) = Math::BigFloat->new($number);
  $big_number->bpow($suffix);
}

while (<>) {
    chomp;
    my @parts = split /\b($RE{num}{real}$suffix_re)\b/io;
    foreach my $part (@parts) {
        if ($part =~ m/^($RE{num}{real})($suffix_re)$/io) {
            my ($number, $suffix) = ($1, $2);
            if ($suffix =~ m/^e/i) {
                print un_format_scientific($number, $suffix);
            } else {
                print un_format_bytes($number, $suffix);
            }
        } else {
            print $part;
        }
    }
    print qq{\n};
}
