#!/bin/bash

# To start over from scratch, rm -rf "${DIR}" and run this.
# See https://flexget.readthedocs.io/en/latest/develop/index.html#how-do-i-get-started

set -e -f -u -o pipefail

# Stop git looking for a commit message when 'git pull' is run.
GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT

readonly DIR="${1:-${HOME}/src/upstream-flexget}"
readonly SCRIPT="bin/activate"

if [ ! -d "${DIR}" ]; then
  # Initial setup
  echo "Updating homebrew and installing python."
  brew update
  brew upgrade
  brew install python
  echo "Cloning will take a long time"
  git clone git@github.com:tobinjt/Flexget.git "${DIR}"
  cd "${DIR}"
  git remote add upstream https://github.com/Flexget/Flexget
fi

cd "${DIR}"
echo "Updating local repository from upstream and pushing to github"
git checkout develop
git pull upstream develop
git merge develop
git pull origin
git push origin

if [ ! -f "${SCRIPT}" ]; then
  # Set up virtualenv.
  echo "Setting up virtualenv"
  pip3 install virtualenv
  virtualenv --clear "${DIR}"
fi

# Dummy values needed by ${SCRIPT}.
export PS1="dummy"
# shellcheck source=/dev/null
source "${SCRIPT}"
if ! pip3 install -e .; then
  echo "pip failed, cleaning up and restarting to run pip again"
  # The most likely reason for failure is that I upgraded Python and so paths
  # are incorrect; remove $SCRIPT and start over.
  # virtualenv will die horribly if any of these exist, so nuke them.
  rm -rf bin include .Python
  # Start over to install supporting tools rather than duplicating it.
  exec "$0" "$@"
fi
pip3 install -r dev-requirements.txt
