#!/bin/bash

set -e -f -u -o pipefail

update_workflows() {
  retry "update Github workflows: ${PWD}" -- ./.github/dependabot.yml
  if ! git check-local-copy-is-clean --ignore-unpushed-commits; then
    git add --all .
    git commit --quiet --message "chore: update Github workflows"
  fi
}

update_rust_dependencies() {
  # `cargo update` doesn't always update dependencies, neither does Dependabot,
  # and nothing seems to remove unnecessary dependencies from Cargo.lock :(
  # Workaround this by deleting Cargo.lock and regenerating it.
  rm -f Cargo.lock
  retry "update Rust dependencies: ${PWD}" -- cargo upgrade
  if ! git check-local-copy-is-clean --ignore-unpushed-commits; then
    git add --all .
    git commit --quiet --message "chore: update Rust dependencies"
  fi
}

update_pre_commit() {
  retry "update pre-commit config: ${PWD}" -- ./.pre-commit-config.yaml
  if ! git check-local-copy-is-clean --ignore-unpushed-commits; then
    pre-commit run --all-files
    git add --all .
    git commit --quiet --message "chore: update pre-commit configuration"
    install-pre-commit-hooks
  fi
}

main() {
  # Skip repos that I cannot push to.
  if git transport-is-https; then
    return
  fi
  # Skip forked repos, I should not be updating pre-commit hooks there.
  if git remote show | grep -q upstream; then
    return
  fi
  if git config remote.origin.url >& /dev/null; then
    GIT_MERGE_AUTOEDIT=no git pull
  fi

  if [[ -x ./setup ]]; then
    ./setup
  fi
  if [[ -x ".github/dependabot.yml" ]]; then
    update_workflows
  fi
  if [[ -x ".pre-commit-config.yaml" ]]; then
    update_pre_commit
  fi
  if [[ -f "Cargo.toml" ]]; then
    update_rust_dependencies
  fi
  if git config remote.origin.url >& /dev/null; then
    git push
  fi
}

main "$@"
