#!/bin/bash

set -e -f -u -o pipefail

warn() {
  echo -e "$@" 1>&2
}
die() {
  warn "$@"
  exit 1
}

# Suppress Mac OS errors like:
# find: /Users/johntobin/Desktop: Operation not permitted
# find: /Users/johntobin/.Trash: Operation not permitted
# find: /Users/johntobin/Documents: Operation not permitted
# find: /Users/johntobin/Downloads: Operation not permitted
find_sources() {
  find "$1" -maxdepth 2 -mindepth 2 -type d -path "$2/.git" 2> /dev/null \
    | sed -e 's,/.git$,,' \
    | sort
}

dotfiles_sources() {
  find_sources "${HOME}/src" '*dotfiles'
}

bin_sources() {
  find_sources "${HOME}" '*bin'
  find_sources "${HOME}/src" '*bin'
}

check_git_works() {
  if ! git help status > /dev/null; then
    printf "Failed to run git.\\n" >&2
    printf "On MacOS install it with 'xcode-select --install'\\n" >&2
    exit 1
  fi
}

need_ssh_agent() {
  local dir
  for dir in $(bin_sources) $(dotfiles_sources); do
    if (cd "${dir}" && git transport-is-ssh); then
      return 0
    fi
  done
  return 1
}

check_ssh_agent() {
  if ! ssh-add -l > /dev/null; then
    ssh-add -l || true
    die "Problem with ssh agent"
  fi
  # Can't check for ${HOME} because that's not consistent across machines; the
  # forwarded key from my laptop will have ${HOME} from my laptop rather than
  # ${HOME} on the destination.
  if [[ -z "$(ssh-add -l | grep /.ssh/ || true)" ]]; then
    die "No ssh keys found"
  fi
}

update_git_checkout_and_push() {
  if [[ "$#" -ne 1 ]]; then
    die "update_git_checkout_and_push needs one argument, got $#"
  fi
  local dir="$1"
  echo "Processing ${dir}"

  # Refuse to do anything if there are uncommitted changes.
  # If there are deleted submodules hanging around clean them up with:
  # $ git clean -f -f -d
  git check-local-copy-is-clean --ignore-unpushed-commits

  # Explicitly enable the old default behaviour so that git doesn't spew
  # warnings.
  git config pull.rebase false
  # Always pull and update submodules.  Note that if we fail before submodules
  # are completely updated there will be uncomitted changes that must be dealt
  # with manually.
  git pull
  git submodule init
  git submodule update
  # Removed submodules won't be deleted by git pull, so we need to clean up.
  # -d removes directories, -f makes removal happen for normal files (but I
  # don't think that's necessary for tracked deletions), and the second -f makes
  # submodules be deleted.
  # Note that if 1) a submodue was deleted and 2) this program crashes after the
  # pull but before the clean happens, this program can't recover on a future
  # run: manual cleanup is necessary.
  git clean -f -f -d

  # We can't push to https:// URLs.
  if ! git transport-is-https; then
    git push
  fi
}

main() {
  if [[ "$#" -ne 0 ]]; then
    warn "Unexpected arguments: $*"
    die "Usage: $0"
  fi
  check_git_works
  # Ensure we have a connection to the ssh agent and keys loaded, if we have ssh
  # origins.
  if need_ssh_agent; then
    check_ssh_agent
  fi
  echo "Running dotfiles to check for pre-existing diffs."
  # First make sure we're up to date so that current diffs aren't mixed in with
  # future diffs.
  dotfiles
  echo "Running dotfiles to check for unexpected files."
  dotfiles -r

  # Update bin dirs.
  local orig_code
  orig_code="$(cat "${BASH_SOURCE[0]}")"
  local dir
  for dir in $(bin_sources); do
    (cd "${dir}" && update_git_checkout_and_push "${dir}")
    # Check for unfinished changes; this happens when submodules are removed
    # because git won't delete the submodule directory.
    (cd "${dir}" && git check-local-copy-is-clean)
  done
  local new_code
  new_code="$(cat "${BASH_SOURCE[0]}")"
  if [[ "${orig_code}" != "${new_code}" ]]; then
    echo "Restarting with updated tools"
    exec "${BASH_SOURCE[0]}"
  fi

  # Check for diffs again with possibly new binaries.
  dotfiles

  # Update all dotfiles.
  for dir in $(dotfiles_sources); do
    (cd "${dir}" && update_git_checkout_and_push "${dir}")
    # Forcibly update.  There is a risk that we clobber a file in our home
    # directory with a file we've just checked out, but the alternative is for
    # the user to forcibly update manually.  This also prevents files that have
    # been deleted from the current repo being left behind in $HOME if updating
    # a later repo fails.
    dotfiles -X -f
    # Check for unfinished changes; this happens when submodules are removed
    # because git won't delete the submodule directory.  Do this after running
    # dotfiles, otherwise there is a high chance that the next run of this
    # program will find diffs and will exit.
    (cd "${dir}" && git check-local-copy-is-clean)
  done
}

# Make sure $HOME/bin is in $PATH to support running
#   "ssh foo@bar update-dotfiles-and-bin"
PATH="${PATH}:${HOME}/bin"
export PATH
main "$@"
