#!/bin/bash

set -e -f -u -o pipefail

main() {
  if [[ "$#" -ne 1 ]]; then
    echo "Usage: $0 VERSION" >&2
    echo "E.g. $0 0.47.2" >&2
    return 1
  fi

  local version="$1"
  readonly version
  if is_mac_os; then
    if is_x86_64; then
      os_type="Darwin_x86_64"
    else
      os_type="Darwin_arm64"
    fi
  else
    os_type="Linux_x86_64"
  fi
  local url="https://github.com/jesseduffield/lazygit/releases/download/"
  url+="v${version}/lazygit_${version}_${os_type}.tar.gz"
  readonly url
  local filename
  filename="$(basename "${url}")"
  readonly filename
  local extraction_dir
  extraction_dir="${HOME}/tmp/lazygit/lazygit.$(date +%Y-%m-%d)"
  readonly extraction_dir

  mkdir -p "${extraction_dir}"
  cd "${extraction_dir}"
  rm -f "${filename}"
  curl --location --output "${filename}" "${url}"
  tar zxvf "$(basename "${url}")"
  ./lazygit --help
  cd ..
  ln -s -f -n "${extraction_dir}/lazygit" lazygit
}

main "$@"
