#!/bin/bash

set -e -f -u -o pipefail

if [[ -z "${CAFFEINATED:-}" ]] && type caffeinate >& /dev/null; then
  CAFFEINATED="do not sleep"
  export CAFFEINATED
  exec caffeinate -i "$0"
fi

dirs_to_update() {
  set +f
  echo "${HOME}/src/"*
  echo "${HOME}/bin"
  set -f
}

update-dotfiles-and-bin
for dir in $(dirs_to_update); do
  if [[ ! -d "${dir}" ]]; then
    continue
  fi
  (cd "${dir}" && retry "update-pre-commit-hooks: ${dir}" \
    -- update-pre-commit-hooks)
  (cd "${dir}" && retry "update-dependencies: ${dir}" \
    -- update-dependencies)
  printf "\n\n\n"
done
