#!/bin/bash

set -e -f -u -o pipefail

update-single-host() {
  local host="$1"
  shift

  printf "\\n\\n\\njohntobin@%s\\n" "${host}"
  retry --press_enter_before_retrying 10 "johntobin@${host}" \
    ssh -o ControlMaster=no -t "johntobin@${host}" \
    "$@"
  printf "\\n\\n\\nroot@%s\\n" "${host}"
  # sudo dscl . -change /Users/root UserShell /bin/sh /bin/bash
  retry --press_enter_before_retrying 10 "root@${host}" \
    ssh -o ControlMaster=no -t "johntobin@${host}" \
    sudo --login "$@"
  printf "\\n\\n\\narianetobin@%s\\n" "${host}"
  retry --press_enter_before_retrying 10 "arianetobin@${host}" \
    ssh -o ControlMaster=no -t \
    "arianetobin@${host}" "$@"
}

main() {
  if [[ "$#" -eq 0 ]]; then
    echo "Usage: $0 update-dotfiles-and-bin | update-dotfiles-and-bin-plugins" \
      >&2
    return 1
  fi

  retry --press_enter_before_retrying 10 "initial update" \
    update-dotfiles-and-bin
  local host
  for host in laptop imac hosting; do
    update-single-host "${host}" "$@"
  done
}

if [[ -z "${CAFFEINATED:-}" ]]; then
  CAFFEINATED="do not sleep"
  export CAFFEINATED
  exec caffeinate -i "$0" "$@"
fi

main "$@"
