#!/bin/bash

set -e -f -u -o pipefail

# Restart with updated code if necessary.
orig_code="$(cat "${BASH_SOURCE[0]}")"
retry update-dotfiles-and-bin -- update-dotfiles-and-bin
new_code="$(cat "${BASH_SOURCE[0]}")"
if [[ "${orig_code}" != "${new_code}" ]]; then
  echo "Restarting with updated tools"
  exec "${BASH_SOURCE[0]}"
fi

if is_mac_os && type brew >& /dev/null; then
  retry brew-update-brew-cleanup -- brew-update-brew-cleanup
elif is_linux && type apt >& /dev/null; then
  retry "apt update" -- sudo apt update
  retry "apt upgrade" -- sudo apt upgrade --assume-yes
fi

# Mason-installed packages are frequently broken by upgrades, reinstall them.
# Do this before anything else because they're used in pre-commit hooks.
retry "Delete Mason packages" -- rm -rf "${HOME}/.local/share/nvim/mason"
retry "Install Mason packages" -- run-nvim-command ":MasonToolsUpdateSync"
retry "Fix vint" -- fix-vint-installation

if type pre-commit >& /dev/null; then
  echo "Updating pre-commit hooks"
  retry update-all-pre-commit-hooks -- update-all-pre-commit-hooks
fi
echo "Installing extra development tools"
retry install-extra-development-tools -- install-extra-development-tools

if [[ -f "/Applications/AdGuardHome/AdGuardHome" ]]; then
  retry AdGuard -- update-adguard
fi
if [[ -d "${HOME}/tmp/bin/lazygit" ]]; then
  retry update-lazygit -- update-lazygit
fi
if [[ -d "${HOME}/tmp/bin/nvim" ]]; then
  retry update-nvim -- update-nvim
fi
if [[ -d "${HOME}/tmp/bin/virtualenv" ]]; then
  retry update-python-modules -- update-python-modules
fi
# This ensures that updates to ~/src/ariane-theme are committed *before* we try
# to update Wordpress.
if [[ -d "${HOME}/src/dev.arianetobin.ie" ]]; then
  retry update-ariane-theme -- update-ariane-theme
fi
if [[ -d "${HOME}/wordpress" ]]; then
  retry update-all-wordpress -- update-all-wordpress
fi
