#!/bin/bash

set -e -f -u -o pipefail

main() {
  if [[ "$#" -ne 1 ]]; then
    echo "Usage: $0 VERSION" >&2
    echo "E.g. $0 0.47.2" >&2
    return 1
  fi

  local version="$1"
  readonly version
  local url="https://github.com/jesseduffield/lazygit/releases/download/"
  url+="v${version}/lazygit_${version}_Linux_x86_64.tar.gz"
  readonly url
  local date
  date="$(date +%Y-%m-%d)"
  readonly date
  local extraction_dir="${HOME}/tmp/lazygit/lazygit.${date}"
  readonly extraction_dir

  mkdir -p "${extraction_dir}"
  cd "${extraction_dir}"
  rm -f "$(basename "${url}")"
  wget "${url}"
  tar zxvf "$(basename "${url}")"
  ./lazygit --help
  cd ..
  ln -s -f -n "${extraction_dir}/lazygit" lazygit
}

main "$@"
