#!/bin/bash

set -e -f -u -o pipefail

main() {
  # Check there aren't any diffs.
  update-dotfiles-and-bin

  # I have forked vim-markdown, so pull any changes from upstream.
  cd "${HOME}/src/vim-markdown"
  git checkout master
  git pull upstream master
  git push

  # Update every submodule; only processing ~/src/dotfiles for now, will add
  # more in future if necessary.
  cd "${HOME}/src/dotfiles"
  git submodule update --recursive --remote
  # Commit the changes if any.
  git add -A .
  if ! git check-local-copy-is-clean 2>/dev/null; then
    git commit -m 'Update all plugins.'
  fi

  # Force overwriting and deletion of removed files.
  dotfiles -f -X
  # Push to upstream, update vim helptags, etc.
  update-dotfiles-and-bin
  # Install syntax checkers and other necessary tools.
  install-extra-tools-for-vim
}

# Stop git looking for a commit message when 'git pull' is run.
GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT
main "$@"
