#!/bin/bash

set -e -f -u -o pipefail

usage() {
  cat <<USAGE
$0 [FLAGS]
Flags:
  --install_individually
  --skip_brew
  --skip_flexget
  --skip_python
USAGE
}

test_python() {
  cd "${HOME}/bin/python"
  pytest
  set +f
  mypy -- *.py
  set -f
}

test_flexget() {
  printf "\\n\\nTesting Flexget\\n"
  flexget-wrapper execute
  printf "\\n\\n\\n\\n\\n"
}

venv_install() {
  local destdir="$1" install_individually="$2" test_function="$3"
  shift 3
  local date
  date="$(date +%Y-%m-%d--%H-%M-%S)"
  local destdir_date="${destdir}-${date}"

  mkdir -p "${destdir}"
  cd "${destdir}"
  python3 -m venv "${destdir_date}"
  cd "${destdir_date}"
  source bin/activate

  if [[ "${install_individually}" -eq 0 ]]; then
    # Install everything at once so that dependencies get resolved properly
    # across packages.
    pip3 install "$@"
  else
    # Install packages one by one so that it's easier to figure out which
    # package is broken when something goes wrong.
    local package
    for package in "$@"; do
      printf "\n\npip3 install %s\\n" "${package}"
      pip3 install "${package}"
    done
  fi
  deactivate

  # Test with the new binaries, from $HOME, just in case.
  cd "${HOME}"
  PATH="${destdir_date}/bin:${PATH}"
  hash -r
  ("${test_function}")

  if is_mac_os; then
    # -h: don't follow a destination symlink, replace it instead.
    ln -sfh "${destdir_date}" "${destdir}"
  else
    # -n: don't follow a destination symlink, replace it instead.
    ln -sfn "${destdir_date}" "${destdir}"
  fi
}

main() {
  local skip_flexget=0 skip_python=0 install_individually=0
  while [[ "$#" -gt 0 ]]; do
    case "${1}" in
      --install_individually)
        install_individually=1
        shift
        ;;
      --skip_flexget)
        skip_flexget=1
        shift
        ;;
      --skip_python)
        skip_python=1
        shift
        ;;
      *)
        usage >&2
        return 1
        ;;
    esac
  done

  # Let Python write bytecode.
  unset PYTHONPYCACHEPREFIX PYTHONDONTWRITEBYTECODE
  if type brew >&/dev/null; then
    # Update all existing Homebrew packages so that if I'm using Homebrew Python
    # the venv will point at the right Python.
    brew-update-brew-cleanup
  fi
  if is_linux && type apt >&/dev/null; then
    sudo apt install python3 python3-pip
  fi

  # Environment values needed by activate scripts.
  export PS1="needed-by-activate-scripts"

  # I tried using homebrew packages for some tools, but that lead to a terrible
  # mix of Python versions and tools not finding modules so I reverted to using
  # Pip for everything.

  local venv_dir="${HOME}/tmp/bin/virtualenv"
  readonly venv_dir
  mkdir -p "${venv_dir}"

  # Install all Python development tools in a single venv so all the
  # modules are easily available at the same time, particularly debugpy.
  # https://pypi.org/project/python-lsp-server/ - install all supported plugins.
  if [[ "${skip_python}" -eq 0 ]]; then
    local python_dir="${venv_dir}/python"
    # Run in a subshell because it changes directory.
    (venv_install "${python_dir}" "${install_individually}" test_python \
      black \
      debugpy \
      dnspython \
      identify \
      mypy \
      pudb \
      pydantic \
      pyfakefs \
      pytest \
      pytest-cov \
      pytest-flakefinder \
      pytest-timeout \
      pyyaml \
      requests \
      retry \
      types-PyYAML\
      types-requests \
      types-retry \
    )
  fi

  # Flexget.  Only install and test on machines where I normally run flexget.
  if [[ "${skip_flexget}" -eq 0 && -d "${HOME}/tmp/logs/flexget" ]]; then
    # Run in a subshell because it changes directory.
    (venv_install "${venv_dir}/flexget" "${install_individually}" \
      test_flexget \
      "flexget" \
      "legacy-cgi" \
      "transmission-rpc")
  fi
}

if [[ -z "${CAFFEINATED:-}" ]] && type caffeinate >&/dev/null; then
  CAFFEINATED="do not sleep"
  export CAFFEINATED
  exec caffeinate -i "$0"
fi

main "$@"
