#!/bin/bash

set -e -f -u -o pipefail

PATH="${HOME}/bin:${PATH}"

commit_all() {
  local dir="$1"
  local subdir="wp-content/themes/ariane-theme"

  # Check for local changes.
  cd "${dir}/${subdir}"
  git check-local-copy-is-clean --ignore-unpushed-commits
  # Sync with upstream.
  git pull
  git push
  # Update parent repo so that backups and updates work.
  cd "${dir}"
  if ! git check-local-copy-is-clean 2>/dev/null; then
    git add "wp-content/themes/ariane-theme"
    git commit -m 'Updated ariane-theme.'
  fi
  git check-local-copy-is-clean
}

main() {
  if [[ "$#" -eq 0 ]]; then
    # Update dev.
    commit_all "${HOME}/dev.arianetobin.ie"
    # Update www.
    ssh -o ControlMaster=no arianetobin@hosting \
      "${HOME}/bin/update-ariane-theme" argument_just_to_trigger_other_branch
    # Clear mod_pagespeed cache to ensure consistency, e.g. correct style.css
    # being used.
    sudo touch /var/cache/mod_pagespeed/cache.flush
  else
    # This is being run over ssh as arianetobin.
    commit_all "${HOME}/arianetobin.ie/"
  fi
}

main "$@"
