#!/bin/bash

set -e -f -u -o pipefail

retry() {
  local sleep_time=10
  until "$@"; do
    sleep "${sleep_time}"
  done
}

retry update-dotfiles-and-bin
echo; echo; echo; echo "root@localhost"
echo "password for root:"
# This only works when root's shell is bash.
# sudo dscl . -change /Users/root UserShell /bin/sh /bin/bash
retry sudo --login update-dotfiles-and-bin

echo; echo; echo; echo "johntobin@mini"
retry ssh -t mini update-dotfiles-and-bin
echo; echo; echo; echo "root@mini"
echo "password for root@mini:"
retry ssh -t mini sudo --login update-dotfiles-and-bin
echo; echo; echo; echo "arianetobin@mini"
retry ssh -t arianetobin@mini update-dotfiles-and-bin

echo; echo; echo; echo "johntobin@hosting"
retry ssh -t hosting update-dotfiles-and-bin
echo; echo; echo; echo "root@hosting"
echo "password for root@hosting:"
retry ssh -t hosting sudo --login update-dotfiles-and-bin
echo; echo; echo; echo "ariane@hosting"
retry ssh -t ariane@hosting update-dotfiles-and-bin
