#!/bin/bash

set -e -f -u -o pipefail

# Keep the laptop awake.
if [[ -z "${CAFFEINATED:-}" ]] && type caffeinate >& /dev/null; then
  CAFFEINATED="do not sleep"
  export CAFFEINATED
  exec caffeinate -i "$0"
fi

# Restart with updated code if necessary.
orig_code="$(cat "${BASH_SOURCE[0]}")"
retry update-dotfiles-and-bin -- update-dotfiles-and-bin
new_code="$(cat "${BASH_SOURCE[0]}")"
if [[ "${orig_code}" != "${new_code}" ]]; then
  echo "Restarting with updated tools"
  exec "${BASH_SOURCE[0]}"
fi

if is_mac_os && type brew >& /dev/null; then
  retry brew-update-brew-cleanup -- brew-update-brew-cleanup
elif is_linux && type apt >& /dev/null && groups | grep -w -q sudo; then
  retry "apt update" -- sudo apt update
  retry "apt upgrade" -- sudo apt upgrade --assume-yes
fi

# Mason-installed packages are frequently broken by upgrades, reinstall them.
# Do this before anything else because they're used in pre-commit hooks.
retry "Delete Mason packages" -- rm -rf "${HOME}/.local/share/nvim/mason"
if type nvim >& /dev/null; then
  retry "Install Mason packages" -- \
    run-nvim-command \
      'lua require("johntobin.functions").RunCommandIfExists("MasonToolsUpdateSync")'
fi

if type pre-commit >& /dev/null; then
  echo "Updating pre-commit hooks"
  retry update-all-pre-commit-hooks -- update-all-pre-commit-hooks
fi
echo "Installing extra development tools"
retry install-extra-development-tools -- install-extra-development-tools

if [[ -f "/Applications/AdGuardHome/AdGuardHome" ]]; then
  retry AdGuard -- update-adguard
fi
if [[ -d "${HOME}/tmp/bin/lazygit" ]]; then
  retry update-lazygit -- update-lazygit
fi
if [[ -d "${HOME}/tmp/bin/nvim" ]]; then
  retry update-nvim -- update-nvim
fi
if [[ -d "${HOME}/tmp/bin/virtualenv" ]]; then
  retry update-python-modules -- update-python-modules
fi
if [[ -d "${HOME}/src/hugo-coder" ]]; then
  retry update-hugo-coder -- update-hugo-coder
fi
# This ensures that updates to ~/src/ariane-theme are committed *before* we try
# to update Wordpress.
if [[ -d "${HOME}/src/dev.arianetobin.ie" ]]; then
  retry update-ariane-theme -- update-ariane-theme
  retry update-all-wordpress -- update-all-wordpress
fi

# Update any git repo that hasn't already been updated.
set +f
for repo in "${HOME}/src/"*; do
  retry "check-git-repos ${repo}" -- check-git-repos "${repo}"
done
set -f
