#!/bin/bash

set -e -f -u -o pipefail

cd "${HOME}/src/upstream-flexget"
git checkout develop
git pull upstream develop
git merge develop
git push origin
# Dummy values for bin/activate
export PS1="dummy"
source bin/activate
pip install -e .
