#!/bin/bash

set -e -f -u -o pipefail

warn() {
    echo -e "$@" 1>&2
}
die() {
    warn "$@"
    exit 1
}

dotfiles_sources() {
  find "${HOME}/src" -maxdepth 1 -iname '*dotfiles*' -type d
}

bin_sources() {
  find "${HOME}" -maxdepth 1 -iname '*bin*' -type d
}

update_git_checkout_and_push() {
  if [[ "$#" -ne 1 ]]; then
    die "update_git_checkout_and_push needs one argument, got $#"
  fi
  local dir="$1"
  echo "Processing ${dir}"
  cd "${dir}"
  if [[ ! -d ".git" ]]; then
    # Not a git repository.
    return
  fi

  # Refuse to do anything if there are uncommitted changes.
  local git_status
  git_status="$(git status --short)"
  if [[ -n "${git_status}" ]]; then
      die "Uncommitted changes in ${dir}:\n" "${git_status}"
  fi

  # Always pull and update submodules.  Note that if we fail before submodules
  # are completely updated there will be uncomitted changes that must be dealt
  # with manually.
  git pull
  git submodule init
  git submodule update

  # We can't push to https:// URLs.
  local repo_url
  repo_url="$(git config --get remote.origin.url)"
  if [[ "${repo_url:0:8}" != "https://" ]]; then
    git push
  fi
}

main() {
  if [[ "$#" -ne 0 ]]; then
    warn "Unexpected arguments: $@"
    die "Usage: $0"
  fi
  # First make sure we're up to date so that current diffs aren't mixed in with
  # future diffs.
  dotfiles

  # Update bin dirs.
  local dir
  for dir in $(bin_sources); do
    update_git_checkout_and_push "${dir}"
  done

  # Check for diffs again with possibly new binaries.
  dotfiles

  # Update all dotfiles.
  for dir in $(dotfiles_sources); do
    update_git_checkout_and_push "${dir}"
    # Forcibly update.  There is a risk that we clobber a file in our home
    # directory with a file we've just checked out, but the alternative is for
    # the user to forcibly update manually.
    dotfiles -f
  done

  # Report unexpected files.
  dotfiles -r
}

main "$@"
