#!/bin/bash

set -e -f -u -o pipefail

echo "dev.arianetobin.ie"
retry dev.arianetobin.ie -- \
  update-wordpress-core-plugins-and-themes "${HOME}/src/dev.arianetobin.ie"
echo "test.arianetobin.ie"
retry test.arianetobin.ie -- \
  update-wordpress-core-plugins-and-themes "${HOME}/src/test.arianetobin.ie"
read -r -p 'Press enter to update arianetobin.ie'
# I want $HOME to be expanded on the remote side.
# shellcheck disable=SC2016
retry arianetobin.ie -- \
  ssh ar-hosting \
    update-wordpress-core-plugins-and-themes '${HOME}/src/arianetobin.ie'
