#!/bin/bash

set -e -f -u -o pipefail

update_one_dir() {
  if [[ ! -f ".pre-commit-config.yaml" ]]; then
    return
  fi
  if git transport-is-https; then
    return
  fi
  # Skip forked repos, I should not be updating pre-commit hooks there.
  if git remote show | grep -q upstream; then
    return
  fi

  check-git-repos "$(pwd)"
  pre-commit autoupdate
  if ! git check-local-copy-is-clean; then
    pre-commit run --all-files
    git commit -a -m 'chore: Update hooks version.'
    git push
    pre-commit install --install-hooks
  fi
}

update_one_dir
