#!/bin/bash

set -e -f -u -o pipefail

if [[ -z "${CAFFEINATED:-}" ]] && type caffeinate >& /dev/null; then
  CAFFEINATED="do not sleep"
  export CAFFEINATED
  exec caffeinate -i "$0"
fi

dirs_to_update() {
  set +f
  echo "${HOME}/src/"*
  echo "${HOME}/bin"
  set -f
}

update_workflows() {
  retry "update Github workflows: ${PWD}" -- ./.github/dependabot.yml
  if ! git check-local-copy-is-clean; then
    git add --all .
    git commit --quiet --message "chore: update Github workflows"
  fi
}

update_everything() {
  retry "update-pre-commit-hooks: ${dir}" -- update-pre-commit-hooks
  retry "update-dependencies: ${dir}" -- update-dependencies
  if [[ -x "${dir}/.github/dependabot.yml" ]]; then
    update_workflows
  fi
  if git config remote.origin.url >& /dev/null; then
    git push
  fi
}

update-dotfiles-and-bin
for dir in $(dirs_to_update); do
  if [[ ! -d "${dir}" ]]; then
    continue
  fi
  (cd "${dir}" && update_everything)
  printf "\n\n\n"
done
