#!/bin/bash

# To start over from scratch, rm -rf "${DIR}" and run this.
# See https://flexget.readthedocs.io/en/latest/develop/index.html#how-do-i-get-started

set -e -f -u -o pipefail

readonly DIR="${1:-${HOME}/src/upstream-flexget}"
readonly SCRIPT="bin/activate"

if [ ! -d "${DIR}" ]; then
  # Initial setup
  brew update
  brew upgrade
  brew install python
  echo "Cloning will take a long time"
  git clone git@github.com:tobinjt/Flexget.git "${DIR}"
  cd "${DIR}"
  git remote add upstream https://github.com/Flexget/Flexget
fi

cd "${DIR}"
git checkout develop
git pull upstream develop
git merge develop
git pull origin
git push origin

if [ ! -f "${SCRIPT}" ]; then
  # Set up virtualenv.
  pip install virtualenv
  virtualenv --clear "${DIR}"
fi

# Dummy values needed by ${SCRIPT}.
export PS1="dummy"
# shellcheck source=/dev/null
source "${SCRIPT}"
pip install -e .
pip install -r dev-requirements.txt
