#!/bin/bash

set -e -f -u -o pipefail

main() {
  local tmpfile
  tmpfile="$(mktemp -t vim-grep.XXXXXXXXXXXX)"
  if git rev-parse --show-toplevel >& /dev/null; then
    git grep --untracked --line-number "$@" > "${tmpfile}"
  else
    git grep --no-index --line-number "$@" > "${tmpfile}"
  fi
  vim-cfile "${tmpfile}"
  rm -f "${tmpfile}"
}

main "$@"
