#!/usr/bin/env perl

# $Id$
# A perl reimplementation of which that lists ALL occurances of the command in
# your path.

use File::Spec	qw ();

@ARGV
	or die <<USAGE;
Usage: $0 command [. . . ]
List all occurances of command in $PATH.
USAGE

foreach my $command ( @ARGV ) {
	foreach my $dir ( File::Spec->path () ) {
		my $path = File::Spec->catfile ( $dir, $command );
		-x $path or next;
		print $path, "\n";
	}
print "\n";
}
