#!/bin/bash

set -e -f -u -o pipefail

# Only update brew if it's been at least 4 hours since the last update.
old_dir="$(find /usr/local/Homebrew/ -maxdepth 1 -name .git -cmin +240)"
if [[ -n "${old_dir}" ]]; then
  printf "Updating homebrew and checking for new binaries\\n"
  brew update
  for binary in youtube-dl ffmpeg $(brew deps ffmpeg); do
    if brew outdated | grep "^${binary}$"; then
      printf "Updating %s\\n" "${binary}"
      brew upgrade "${binary}"
    fi
  done
fi
until /usr/local/bin/youtube-dl "$@"; do
  sleep 10
done
