#!/bin/bash

set -e -f -u -o pipefail

cd "${HOME}/Downloads/warhammer/"
printf "Updating homebrew to check for new version of youtube-dl\\n"
brew update
if brew outdated | grep youtube-dl; then
  printf "Updating youtube-dl\\n"
  brew upgrade youtube-dl
fi
until /usr/local/bin/youtube-dl "$@"; do
  sleep 10
done
