#!/bin/bash

set -e -f -u -o pipefail

# shellcheck disable=SC1091
source ../check-links

wget() {
  # Ugly way to set ${url} to the last argument.
  for url in "$@"; do
    true
  done
  if [[ "${url}" != "https://www.johntobin.ie/" ]]; then
    printf "Bad URL: %s\\n" "${url}" >&2
    exit 1
  fi
  cat > wget.log <<WGET
# Successful request
--2019-12-12 22:45:34--  https://www.johntobin.ie/
HTTP request sent, awaiting response... 200 OK
# Unsuccessful request
--2019-12-12 22:45:34--  https://www.johntobin.ie/unsuccessful
HTTP request sent, awaiting response... 404 Not found
# Unsuccessful request, succeeds on retry
--2019-12-12 22:45:34--  https://www.johntobin.ie/succeed-on-retry
HTTP request sent, awaiting response... 401 Something went wrong
--2019-12-12 22:45:34--  https://www.johntobin.ie/succeed-on-retry
HTTP request sent, awaiting response... 200 OK
WGET
}

output="$(main "https://www.johntobin.ie/" >&1)"
filtered="$(sed -e '/for further investigation/d' <<<"${output}")"
expected="$(cat <<EXPECTED
Problems found:
--2019-12-12 22:45:34--  https://www.johntobin.ie/unsuccessful HTTP request sent, awaiting response... 404 Not found
EXPECTED
)"
diff -u <(echo "${expected}") <(echo "${filtered}")
