#!/bin/bash

set -e -f -u -o pipefail

DIR="$(mktemp -d -t full-disk-access-XXXXXXXXXX)"
STDOUT="${DIR}/stdout"
STDERR="${DIR}/stderr"
readonly DIR STDOUT STDERR

cc -Weverything -o "${DIR}/full-disk-access" "${HOME}/bin/full-disk-access.c"

"${DIR}/full-disk-access" echo foo >> "${STDOUT}" 2>> "${STDERR}"
"${DIR}/full-disk-access" does-not-exist >> "${STDOUT}" 2>> "${STDERR}" || true
diff -u full-disk-access_test.stdout "${STDOUT}"
diff -u full-disk-access_test.stderr "${STDERR}"
