#!/bin/bash

set -e -f -u -o pipefail

# shellcheck disable=SC1091
source ../path-parents

DIR="$(mktemp -d /tmp/path-parents-XXXXXXXXXX)"
STDOUT="${DIR}/stdout"
STDERR="${DIR}/stderr"
readonly DIR STDOUT STDERR

die() {
  echo "$@" >&2
  exit 1
}

# Run a command and check the exit code.
check_command_fails() {
  if main "$@" >> "${STDOUT}" 2>> "${STDERR}"; then
    die "Command succeeded: $*"
  fi
}
check_command_succeeds() {
  if ! main "$@" >> "${STDOUT}" 2>> "${STDERR}"; then
    die "Command failed: $*"
  fi
}

# Log a message to stdout and stderr logs to easily tell where output starts and
# ends.
start_test() {
  local file
  for file in "${STDOUT}" "${STDERR}"; do
    echo ">>> $* <<<" >> "${file}"
  done
}

test_main() {
  # Argument handling.
  start_test "No args"
  check_command_fails
  start_test "One filename"
  check_command_succeeds /etc/passwd
  start_test "Non-existent filename works"
  check_command_succeeds /qwerty/asdf/bar/foo/baz
  start_test "Only -h"
  check_command_succeeds -h
  start_test "Valid -s"
  check_command_succeeds -s 1 /etc/passwd
  start_test "Invalid -s"
  check_command_fails -s asdf /etc/passwd
  start_test "Unrecognised option"
  check_command_fails -q /etc/passwd

  # Path variants.
  start_test "Leading slashes"
  check_command_succeeds /etc/passwd
  check_command_succeeds -s 1 /etc/passwd
  start_test "No leading slashes"
  check_command_succeeds etc/passwd
  check_command_succeeds -s 1 etc/passwd
  start_test "Doubled slashes"
  check_command_succeeds etc//passwd
  check_command_succeeds -s 1 //etc/passwd
  check_command_succeeds -s 2 qwerty//asdf//bar/foo//baz

  start_test "Running out of components."
  check_command_succeeds -s 3 etc//passwd
  check_command_succeeds -s 10 /qwerty/asdf/bar/foo/baz

  start_test "Reading from stdin."
  echo "/qwerty/asdf/bar/foo/baz" | check_command_succeeds
  start_test "Reading from stdin and skipping."
  echo "/qwerty/asdf/bar/foo/baz" | check_command_succeeds -s 3

  diff -u path-parents_test.stdout "${STDOUT}"
  diff -u path-parents_test.stderr "${STDERR}"
  rm -r -f "${DIR}"
}

test_main
touch .path-parents_timestamp
