#!/bin/bash

set -e -f -u -o pipefail

source ../path-parents

die() {
  echo "$@" >&2
  exit 1
}

# Run a command and check the exit code.
check_command_fails() {
  if main "$@"; then
    die "Command succeeded: $*"
  fi
}
check_command_succeeds() {
  if ! main "$@"; then
    die "Command failed: $*"
  fi
}

# Log a message to stdout and stderr logs to easily tell where output starts and
# ends.
start_test() {
  echo ">>> $* <<<"
  echo ">>> $* <<<" >&2
}

# Argument handling.
start_test "One filename"
check_command_succeeds /etc/passwd
start_test "Non-existent filename works"
check_command_succeeds /qwerty/asdf/bar/foo/baz
start_test "Only -h"
check_command_succeeds -h
start_test "Valid -s"
check_command_succeeds -s 1 /etc/passwd
start_test "Invalid -s"
check_command_fails -s asdf /etc/passwd
start_test "Unrecognised option"
check_command_fails -q /etc/passwd
start_test "No args reads stdin"
check_command_succeeds < <(echo /a/b/c)

# Path variants.
start_test "Leading slashes"
check_command_succeeds /etc/passwd
check_command_succeeds -s 1 /etc/passwd
start_test "No leading slashes"
check_command_succeeds etc/passwd
check_command_succeeds -s 1 etc/passwd
start_test "Doubled slashes"
check_command_succeeds etc//passwd
check_command_succeeds -s 1 //etc/passwd
check_command_succeeds -s 2 qwerty//asdf//bar/foo//baz

start_test "Running out of components."
check_command_succeeds -s 3 etc//passwd
check_command_succeeds -s 10 /qwerty/asdf/bar/foo/baz

start_test "Reading from stdin."
echo "/qwerty/asdf/bar/foo/baz" | check_command_succeeds
start_test "Reading from stdin and skipping."
echo "/qwerty/asdf/bar/foo/baz" | check_command_succeeds -s 3
