#!/bin/bash

set -e -f -u -o pipefail

# Wrap a test program and compare the output to golden outputs.
# This makes the test programs simpler to debug.

stdout="$(mktemp -t stdout.XXXXXXXXXXXXXXXXX)"
stderr="$(mktemp -t stderr.XXXXXXXXXXXXXXXXX)"
test_program="$1"
if ! "${test_program}" > "${stdout}" 2> "${stderr}"; then
  printf "Test program %s failed\\n" "${test_program}"
  return 1
fi

diff -u "${test_program}.stdout" "${stdout}"
diff -u "${test_program}.stderr" "${stderr}"
rm -f "${stdout}" "${stderr}"
# ./foo_test => ./foo_timestamp => .foo_timestamp
timestamp="${test_program%_test}_timestamp"
timestamp=".${timestamp#./}"
touch "${timestamp}"
