version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    # Group updates into one PR.
    groups:
      go-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    # Group updates into one PR.
    groups:
      cargo-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    # Group updates into one PR.
    groups:
      pip-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
