name: Go pre-commit checks.
on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  pre-commit-checks:
    name: |
      Run `goimports`, `golangci-lint`, `govulncheck`, and `go test`.
      Commits any changes made by `goimports`.
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push new commits.
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v7.0.0
        with:
          # Ensure we are on the PR branch, not a detached head
          ref: ${{ github.head_ref }}
          # Required to push new commits.
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version: 'stable'
          cache: true # Automatically caches Go modules and build cache

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check imports and formatting
        run: goimports .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.2.0
        with:
          commit_message: "style: automatic fixes by `goimports`"
          file_pattern: '*.go'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0

      - name: Govulncheck
        uses: golang/govulncheck-action@v1.0.4
        with:
          repo-checkout: false

      - name: Run Tests
        run: go test -v -parallel=8 -race -coverprofile=coverage.out ./...
