name: Deploy Hugo site to Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build the site.
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: github-pages
    env:
      TZ: Europe/Dublin
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
        with:
          submodules: recursive
          fetch-depth: 0
          # Ensure we are on the PR branch, not a detached head
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
      - name: Build the site
        run: hugo build --minify
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public # Hugo's default output folder

  # This is a separate action so that if build fails deployment won't be
  # attempted.
  deploy:
    name: Deploy the site.
    environment:
      name: github-pages
    permissions:
      pages: write # Needed to upload to Github pages.
      id-token: write # Needed to self-identify to upload pages.
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
