name: Security Audit

on:
  # Scan on push to main and for all Pull Requests
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  # Scan every day at midnight to catch new advisories
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  audit-dependencies:
    runs-on: ubuntu-latest
    name: Runs `cargo audit`.
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run cargo-audit
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
