version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group updates to reduce PR noise
    groups:
      go-dependencies:
        patterns:
          - "*"
    # Ensure it updates the go.sum file correctly
    versioning-strategy: increase
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group updates to reduce PR noise
    groups:
      cargo-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
