#!/usr/bin/env python3
"""Script to generate a GitHub Actions release workflow for a Rust project."""

import argparse
import os


def generate_workflow(program_name: str, output_shell_completion: bool = False) -> str:
    """Generates a GitHub Actions workflow for releasing a Rust program.

    Args:
        program_name: The name of the program/binary.
        output_shell_completion: Whether to include steps to generate shell completions.

    Returns:
        The generated YAML content as a string.
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    template_path = os.path.join(script_dir, "rust_release_workflow.template")
    with open(template_path, "r", encoding="utf-8") as f:
        template = f.read()

    if output_shell_completion:
        completion_steps = """
          # 1.1 Generate shell completions
          mkdir -p staging/completions
          BIN="target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}"

          $BIN --output_shell_completion bash       > staging/completions/{program_name}.bash
          $BIN --output_shell_completion elvish     > staging/completions/{program_name}.elv
          $BIN --output_shell_completion fish       > staging/completions/{program_name}.fish
          $BIN --output_shell_completion powershell > staging/completions/_{program_name}.ps1
          $BIN --output_shell_completion zsh        > staging/completions/_{program_name}
"""
        insertion_point = "cp LICENSE staging/ || true"
        template = template.replace(
            insertion_point, insertion_point + "\n" + completion_steps
        )

        header_search = "# Generated by `make_rust_github_workflow.py {program_name}`"
        header_replace = (
            "# Generated by `make_rust_github_workflow.py {program_name} "
            "--output_shell_completion`"
        )
        template = template.replace(header_search, header_replace)

    return template.replace("{program_name}", program_name).rstrip()


def main() -> None:
    """Parses arguments and prints the generated workflow."""
    parser = argparse.ArgumentParser(
        description="Generate a GitHub Actions release workflow for a Rust project."
    )
    parser.add_argument("program_name", help="The name of the program to release.")
    parser.add_argument(
        "--output_shell_completion",
        action="store_true",
        help="Include steps to generate shell completions.",
    )
    args = parser.parse_args()

    print(
        generate_workflow(
            args.program_name,  # pyright: ignore [reportAny]
            args.output_shell_completion,  # pyright: ignore [reportAny]
        )
    )


if __name__ == "__main__":
    main()
