import io
import os
import sys
import unittest
from contextlib import redirect_stdout
from typing import override
from unittest import mock

from pyfakefs import fake_filesystem_unittest

import make_rust_github_workflow


class TestMakeGithubWorkflow(unittest.TestCase):
    def test_generate_workflow(self) -> None:
        """Tests that the workflow generation produces expected content."""
        program_name = "testapp"
        content = make_rust_github_workflow.generate_workflow(program_name)

        # Check for shebang
        self.assertTrue(
            content.startswith("#!/usr/bin/env -S make_rust_github_workflow.py testapp")
        )

        # Check for key sections and program name replacement
        self.assertIn("name: Release", content)
        self.assertIn(f"bin: {program_name}", content)
        self.assertIn(f"name: {program_name}-linux-x86_64.tar.gz", content)
        self.assertIn(f"name: {program_name}-macos-x86_64.tar.gz", content)
        self.assertIn(f"name: {program_name}-macos-arm64.tar.gz", content)

        # Check for the bash parameter expansion line
        # It should look like: VERSIONED_NAME="${VERSIONED_NAME/testapp-/testapp-${{ github.ref_name }}-}"
        expected_line = (
            f'VERSIONED_NAME="${{VERSIONED_NAME/{program_name}-/'
            f'{program_name}-${{{{ github.ref_name }}}}-}}"'
        )
        self.assertIn(expected_line, content)

        # Check that completions are NOT present by default
        self.assertNotIn("Generate shell completions", content)
        self.assertNotIn("--output_shell_completion", content)

    def test_generate_workflow_with_completions(self) -> None:
        """Tests that shell completions are included when requested."""
        program_name = "testapp"
        content = make_rust_github_workflow.generate_workflow(
            program_name, output_shell_completion=True
        )

        # Check for shebang with flag
        self.assertTrue(
            content.startswith(
                "#!/usr/bin/env -S make_rust_github_workflow.py testapp "
                + "--output_shell_completion"
            )
        )

        # Check for shell completion block
        self.assertIn("# 1.1 Generate shell completions", content)
        self.assertIn(
            f"$BIN --output_shell_completion bash       > staging/completions/{program_name}.bash",
            content,
        )

        # Check for updated header
        expected_header = (
            f"# Generated by `make_rust_github_workflow.py {program_name} "
            "--output_shell_completion`"
        )
        self.assertIn(expected_header, content)

    @mock.patch.object(sys, "argv", ["make_rust_github_workflow.py", "cliapp"])
    def test_main(self) -> None:
        """Tests that the main function correctly prints generated workflow."""
        with io.StringIO() as buf, redirect_stdout(buf):
            make_rust_github_workflow.main()
            output = buf.getvalue()
            self.assertTrue(
                output.startswith(
                    "#!/usr/bin/env -S make_rust_github_workflow.py cliapp"
                )
            )
            self.assertIn("name: Release", output)
            self.assertIn("bin: cliapp", output)
            self.assertNotIn("Generate shell completions", output)

    @mock.patch.object(
        sys,
        "argv",
        [
            "make_rust_github_workflow.py",
            "cliapp",
            "--output_shell_completion",
        ],
    )
    def test_main_with_flag(self) -> None:
        """Tests that the main function respects the completion flag."""
        with io.StringIO() as buf, redirect_stdout(buf):
            make_rust_github_workflow.main()
            output = buf.getvalue()
            self.assertTrue(
                output.startswith(
                    "#!/usr/bin/env -S make_rust_github_workflow.py cliapp "
                    + "--output_shell_completion"
                )
            )
            self.assertIn("name: Release", output)
            self.assertIn("bin: cliapp", output)
            self.assertIn("Generate shell completions", output)


class TestMainWithFile(fake_filesystem_unittest.TestCase):
    @override
    def setUp(self) -> None:
        self.setUpPyfakefs()

    @mock.patch.object(
        sys, "argv", ["make_rust_github_workflow.py", "cliapp", "workflow.yml"]
    )
    def test_main_with_file(self) -> None:
        """Tests that main correctly writes to a file and makes it executable."""
        # Ensure the template file exists in the fake filesystem
        template_dir = os.path.dirname(
            os.path.abspath(make_rust_github_workflow.__file__)
        )
        template_path = os.path.join(template_dir, "rust_release_workflow.template")
        self.fs.add_real_file(  # pyright: ignore [reportUnknownMemberType]
            template_path
        )

        make_rust_github_workflow.main()

        self.assertTrue(os.path.exists("workflow.yml"))
        with open("workflow.yml", "r", encoding="utf-8") as f:
            content = f.read()
            self.assertTrue(
                content.startswith(
                    "#!/usr/bin/env -S make_rust_github_workflow.py cliapp"
                )
            )
            self.assertIn("name: Release", content)
            self.assertIn("bin: cliapp", content)

        # Check permissions
        mode = os.stat("workflow.yml").st_mode
        self.assertTrue(mode & 0o111)  # Executable


if __name__ == "__main__":
    unittest.main()
