name: Code Quality

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Ensure we are on the PR branch, not a detached head
          ref: ${{ github.head_ref }}
          # Required to push new commits.
          persist-credentials: true

      - name: Install Rust toolchain
        run: rustup toolchain install --component clippy
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      # keep-sorted start block=true
      - name: Run cargo build
        run: cargo build --all-features
      - name: Run cargo check
        run: cargo check
      - name: Run cargo clippy
        run: cargo clippy -- --deny warnings
      - name: Run cargo fmt
        run: cargo fmt
      - name: Run cargo llvm-cov test
        run: cargo llvm-cov test
      - name: Run cargo test
        run: cargo test --all-features
      # keep-sorted end

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: automatic rustfmt fixes"
          file_pattern: 'src/**/*.rs'
